/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class BufferedPortImageMono16 extends Contactable {
  private long swigCPtr;

  protected BufferedPortImageMono16(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.BufferedPortImageMono16_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BufferedPortImageMono16 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_BufferedPortImageMono16(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BufferedPortImageMono16() {
    this(yarpJNI.new_BufferedPortImageMono16__SWIG_0(), true);
  }

  public BufferedPortImageMono16(Port port) {
    this(yarpJNI.new_BufferedPortImageMono16__SWIG_1(Port.getCPtr(port), port), true);
  }

  public boolean addOutput(String name) {
    return yarpJNI.BufferedPortImageMono16_addOutput__SWIG_0(swigCPtr, this, name);
  }

  public boolean addOutput(String name, String carrier) {
    return yarpJNI.BufferedPortImageMono16_addOutput__SWIG_1(swigCPtr, this, name, carrier);
  }

  public boolean addOutput(Contact contact) {
    return yarpJNI.BufferedPortImageMono16_addOutput__SWIG_2(swigCPtr, this, Contact.getCPtr(contact), contact);
  }

  public void close() {
    yarpJNI.BufferedPortImageMono16_close(swigCPtr, this);
  }

  public void interrupt() {
    yarpJNI.BufferedPortImageMono16_interrupt(swigCPtr, this);
  }

  public void resume() {
    yarpJNI.BufferedPortImageMono16_resume(swigCPtr, this);
  }

  public int getPendingReads() {
    return yarpJNI.BufferedPortImageMono16_getPendingReads(swigCPtr, this);
  }

  public Contact where() {
    return new Contact(yarpJNI.BufferedPortImageMono16_where(swigCPtr, this), true);
  }

  public String getName() {
    return yarpJNI.BufferedPortImageMono16_getName(swigCPtr, this);
  }

  public ImageMono16 prepare() {
    return new ImageMono16(yarpJNI.BufferedPortImageMono16_prepare(swigCPtr, this), false);
  }

  public boolean unprepare() {
    return yarpJNI.BufferedPortImageMono16_unprepare(swigCPtr, this);
  }

  public void write(boolean forceStrict) {
    yarpJNI.BufferedPortImageMono16_write__SWIG_0(swigCPtr, this, forceStrict);
  }

  public void write() {
    yarpJNI.BufferedPortImageMono16_write__SWIG_1(swigCPtr, this);
  }

  public void writeStrict() {
    yarpJNI.BufferedPortImageMono16_writeStrict(swigCPtr, this);
  }

  public void waitForWrite() {
    yarpJNI.BufferedPortImageMono16_waitForWrite(swigCPtr, this);
  }

  public void setStrict(boolean strict) {
    yarpJNI.BufferedPortImageMono16_setStrict__SWIG_0(swigCPtr, this, strict);
  }

  public void setStrict() {
    yarpJNI.BufferedPortImageMono16_setStrict__SWIG_1(swigCPtr, this);
  }

  public ImageMono16 read(boolean shouldWait) {
    long cPtr = yarpJNI.BufferedPortImageMono16_read__SWIG_0(swigCPtr, this, shouldWait);
    return (cPtr == 0) ? null : new ImageMono16(cPtr, false);
  }

  public ImageMono16 read() {
    long cPtr = yarpJNI.BufferedPortImageMono16_read__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageMono16(cPtr, false);
  }

  public ImageMono16 lastRead() {
    long cPtr = yarpJNI.BufferedPortImageMono16_lastRead(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageMono16(cPtr, false);
  }

  public boolean isClosed() {
    return yarpJNI.BufferedPortImageMono16_isClosed(swigCPtr, this);
  }

  public void setReplier(PortReader reader) {
    yarpJNI.BufferedPortImageMono16_setReplier(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public void setReader(PortReader reader) {
    yarpJNI.BufferedPortImageMono16_setReader(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public void setAdminReader(PortReader reader) {
    yarpJNI.BufferedPortImageMono16_setAdminReader(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public void onRead(ImageMono16 datum) {
    yarpJNI.BufferedPortImageMono16_onRead(swigCPtr, this, ImageMono16.getCPtr(datum), datum);
  }

  public void useCallback(TypedReaderCallbackImageMono16 callback) {
    yarpJNI.BufferedPortImageMono16_useCallback__SWIG_0(swigCPtr, this, TypedReaderCallbackImageMono16.getCPtr(callback), callback);
  }

  public void useCallback() {
    yarpJNI.BufferedPortImageMono16_useCallback__SWIG_1(swigCPtr, this);
  }

  public void disableCallback() {
    yarpJNI.BufferedPortImageMono16_disableCallback(swigCPtr, this);
  }

  public boolean setEnvelope(PortWriter envelope) {
    return yarpJNI.BufferedPortImageMono16_setEnvelope(swigCPtr, this, PortWriter.getCPtr(envelope), envelope);
  }

  public boolean getEnvelope(PortReader envelope) {
    return yarpJNI.BufferedPortImageMono16_getEnvelope(swigCPtr, this, PortReader.getCPtr(envelope), envelope);
  }

  public int getInputCount() {
    return yarpJNI.BufferedPortImageMono16_getInputCount(swigCPtr, this);
  }

  public int getOutputCount() {
    return yarpJNI.BufferedPortImageMono16_getOutputCount(swigCPtr, this);
  }

  public boolean isWriting() {
    return yarpJNI.BufferedPortImageMono16_isWriting(swigCPtr, this);
  }

  public void getReport(PortReport reporter) {
    yarpJNI.BufferedPortImageMono16_getReport(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

  public void setReporter(PortReport reporter) {
    yarpJNI.BufferedPortImageMono16_setReporter(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

  public SWIGTYPE_p_void acquire() {
    long cPtr = yarpJNI.BufferedPortImageMono16_acquire(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void release(SWIGTYPE_p_void handle) {
    yarpJNI.BufferedPortImageMono16_release(swigCPtr, this, SWIGTYPE_p_void.getCPtr(handle));
  }

  public void setTargetPeriod(double period) {
    yarpJNI.BufferedPortImageMono16_setTargetPeriod(swigCPtr, this, period);
  }

  public SWIGTYPE_p_Type getType() {
    return new SWIGTYPE_p_Type(yarpJNI.BufferedPortImageMono16_getType(swigCPtr, this), true);
  }

  public void promiseType(SWIGTYPE_p_Type typ) {
    yarpJNI.BufferedPortImageMono16_promiseType(swigCPtr, this, SWIGTYPE_p_Type.getCPtr(typ));
  }

  public void setInputMode(boolean expectInput) {
    yarpJNI.BufferedPortImageMono16_setInputMode(swigCPtr, this, expectInput);
  }

  public void setOutputMode(boolean expectOutput) {
    yarpJNI.BufferedPortImageMono16_setOutputMode(swigCPtr, this, expectOutput);
  }

  public void setRpcMode(boolean expectRpc) {
    yarpJNI.BufferedPortImageMono16_setRpcMode(swigCPtr, this, expectRpc);
  }

  public Property acquireProperties(boolean readOnly) {
    long cPtr = yarpJNI.BufferedPortImageMono16_acquireProperties(swigCPtr, this, readOnly);
    return (cPtr == 0) ? null : new Property(cPtr, false);
  }

  public void releaseProperties(Property prop) {
    yarpJNI.BufferedPortImageMono16_releaseProperties(swigCPtr, this, Property.getCPtr(prop), prop);
  }

  public void includeNodeInName(boolean flag) {
    yarpJNI.BufferedPortImageMono16_includeNodeInName(swigCPtr, this, flag);
  }

  public boolean setCallbackLock(SWIGTYPE_p_yarp__os__Mutex mutex) {
    return yarpJNI.BufferedPortImageMono16_setCallbackLock(swigCPtr, this, SWIGTYPE_p_yarp__os__Mutex.getCPtr(mutex));
  }

  public boolean removeCallbackLock() {
    return yarpJNI.BufferedPortImageMono16_removeCallbackLock(swigCPtr, this);
  }

  public boolean lockCallback() {
    return yarpJNI.BufferedPortImageMono16_lockCallback(swigCPtr, this);
  }

  public boolean tryLockCallback() {
    return yarpJNI.BufferedPortImageMono16_tryLockCallback(swigCPtr, this);
  }

  public void unlockCallback() {
    yarpJNI.BufferedPortImageMono16_unlockCallback(swigCPtr, this);
  }

}
