/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class BufferedPortImageRgb extends Contactable {
  private long swigCPtr;

  protected BufferedPortImageRgb(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.BufferedPortImageRgb_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BufferedPortImageRgb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_BufferedPortImageRgb(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BufferedPortImageRgb() {
    this(yarpJNI.new_BufferedPortImageRgb__SWIG_0(), true);
  }

  public BufferedPortImageRgb(Port port) {
    this(yarpJNI.new_BufferedPortImageRgb__SWIG_1(Port.getCPtr(port), port), true);
  }

  public boolean addOutput(String name) {
    return yarpJNI.BufferedPortImageRgb_addOutput__SWIG_0(swigCPtr, this, name);
  }

  public boolean addOutput(String name, String carrier) {
    return yarpJNI.BufferedPortImageRgb_addOutput__SWIG_1(swigCPtr, this, name, carrier);
  }

  public boolean addOutput(Contact contact) {
    return yarpJNI.BufferedPortImageRgb_addOutput__SWIG_2(swigCPtr, this, Contact.getCPtr(contact), contact);
  }

  public void close() {
    yarpJNI.BufferedPortImageRgb_close(swigCPtr, this);
  }

  public void interrupt() {
    yarpJNI.BufferedPortImageRgb_interrupt(swigCPtr, this);
  }

  public void resume() {
    yarpJNI.BufferedPortImageRgb_resume(swigCPtr, this);
  }

  public int getPendingReads() {
    return yarpJNI.BufferedPortImageRgb_getPendingReads(swigCPtr, this);
  }

  public Contact where() {
    return new Contact(yarpJNI.BufferedPortImageRgb_where(swigCPtr, this), true);
  }

  public String getName() {
    return yarpJNI.BufferedPortImageRgb_getName(swigCPtr, this);
  }

  public ImageRgb prepare() {
    return new ImageRgb(yarpJNI.BufferedPortImageRgb_prepare(swigCPtr, this), false);
  }

  public boolean unprepare() {
    return yarpJNI.BufferedPortImageRgb_unprepare(swigCPtr, this);
  }

  public void write(boolean forceStrict) {
    yarpJNI.BufferedPortImageRgb_write__SWIG_0(swigCPtr, this, forceStrict);
  }

  public void write() {
    yarpJNI.BufferedPortImageRgb_write__SWIG_1(swigCPtr, this);
  }

  public void writeStrict() {
    yarpJNI.BufferedPortImageRgb_writeStrict(swigCPtr, this);
  }

  public void waitForWrite() {
    yarpJNI.BufferedPortImageRgb_waitForWrite(swigCPtr, this);
  }

  public void setStrict(boolean strict) {
    yarpJNI.BufferedPortImageRgb_setStrict__SWIG_0(swigCPtr, this, strict);
  }

  public void setStrict() {
    yarpJNI.BufferedPortImageRgb_setStrict__SWIG_1(swigCPtr, this);
  }

  public ImageRgb read(boolean shouldWait) {
    long cPtr = yarpJNI.BufferedPortImageRgb_read__SWIG_0(swigCPtr, this, shouldWait);
    return (cPtr == 0) ? null : new ImageRgb(cPtr, false);
  }

  public ImageRgb read() {
    long cPtr = yarpJNI.BufferedPortImageRgb_read__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageRgb(cPtr, false);
  }

  public ImageRgb lastRead() {
    long cPtr = yarpJNI.BufferedPortImageRgb_lastRead(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageRgb(cPtr, false);
  }

  public boolean isClosed() {
    return yarpJNI.BufferedPortImageRgb_isClosed(swigCPtr, this);
  }

  public void setReplier(PortReader reader) {
    yarpJNI.BufferedPortImageRgb_setReplier(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public void setReader(PortReader reader) {
    yarpJNI.BufferedPortImageRgb_setReader(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public void setAdminReader(PortReader reader) {
    yarpJNI.BufferedPortImageRgb_setAdminReader(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public void onRead(ImageRgb datum) {
    yarpJNI.BufferedPortImageRgb_onRead(swigCPtr, this, ImageRgb.getCPtr(datum), datum);
  }

  public void useCallback(TypedReaderCallbackImageRgb callback) {
    yarpJNI.BufferedPortImageRgb_useCallback__SWIG_0(swigCPtr, this, TypedReaderCallbackImageRgb.getCPtr(callback), callback);
  }

  public void useCallback() {
    yarpJNI.BufferedPortImageRgb_useCallback__SWIG_1(swigCPtr, this);
  }

  public void disableCallback() {
    yarpJNI.BufferedPortImageRgb_disableCallback(swigCPtr, this);
  }

  public boolean setEnvelope(PortWriter envelope) {
    return yarpJNI.BufferedPortImageRgb_setEnvelope(swigCPtr, this, PortWriter.getCPtr(envelope), envelope);
  }

  public boolean getEnvelope(PortReader envelope) {
    return yarpJNI.BufferedPortImageRgb_getEnvelope(swigCPtr, this, PortReader.getCPtr(envelope), envelope);
  }

  public int getInputCount() {
    return yarpJNI.BufferedPortImageRgb_getInputCount(swigCPtr, this);
  }

  public int getOutputCount() {
    return yarpJNI.BufferedPortImageRgb_getOutputCount(swigCPtr, this);
  }

  public boolean isWriting() {
    return yarpJNI.BufferedPortImageRgb_isWriting(swigCPtr, this);
  }

  public void getReport(PortReport reporter) {
    yarpJNI.BufferedPortImageRgb_getReport(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

  public void setReporter(PortReport reporter) {
    yarpJNI.BufferedPortImageRgb_setReporter(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

  public SWIGTYPE_p_void acquire() {
    long cPtr = yarpJNI.BufferedPortImageRgb_acquire(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void release(SWIGTYPE_p_void handle) {
    yarpJNI.BufferedPortImageRgb_release(swigCPtr, this, SWIGTYPE_p_void.getCPtr(handle));
  }

  public void setTargetPeriod(double period) {
    yarpJNI.BufferedPortImageRgb_setTargetPeriod(swigCPtr, this, period);
  }

  public SWIGTYPE_p_Type getType() {
    return new SWIGTYPE_p_Type(yarpJNI.BufferedPortImageRgb_getType(swigCPtr, this), true);
  }

  public void promiseType(SWIGTYPE_p_Type typ) {
    yarpJNI.BufferedPortImageRgb_promiseType(swigCPtr, this, SWIGTYPE_p_Type.getCPtr(typ));
  }

  public void setInputMode(boolean expectInput) {
    yarpJNI.BufferedPortImageRgb_setInputMode(swigCPtr, this, expectInput);
  }

  public void setOutputMode(boolean expectOutput) {
    yarpJNI.BufferedPortImageRgb_setOutputMode(swigCPtr, this, expectOutput);
  }

  public void setRpcMode(boolean expectRpc) {
    yarpJNI.BufferedPortImageRgb_setRpcMode(swigCPtr, this, expectRpc);
  }

  public Property acquireProperties(boolean readOnly) {
    long cPtr = yarpJNI.BufferedPortImageRgb_acquireProperties(swigCPtr, this, readOnly);
    return (cPtr == 0) ? null : new Property(cPtr, false);
  }

  public void releaseProperties(Property prop) {
    yarpJNI.BufferedPortImageRgb_releaseProperties(swigCPtr, this, Property.getCPtr(prop), prop);
  }

  public void includeNodeInName(boolean flag) {
    yarpJNI.BufferedPortImageRgb_includeNodeInName(swigCPtr, this, flag);
  }

  public boolean setCallbackLock(SWIGTYPE_p_yarp__os__Mutex mutex) {
    return yarpJNI.BufferedPortImageRgb_setCallbackLock(swigCPtr, this, SWIGTYPE_p_yarp__os__Mutex.getCPtr(mutex));
  }

  public boolean removeCallbackLock() {
    return yarpJNI.BufferedPortImageRgb_removeCallbackLock(swigCPtr, this);
  }

  public boolean lockCallback() {
    return yarpJNI.BufferedPortImageRgb_lockCallback(swigCPtr, this);
  }

  public boolean tryLockCallback() {
    return yarpJNI.BufferedPortImageRgb_tryLockCallback(swigCPtr, this);
  }

  public void unlockCallback() {
    yarpJNI.BufferedPortImageRgb_unlockCallback(swigCPtr, this);
  }

}
