/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class BVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_BVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BVector() {
    this(yarpJNI.new_BVector__SWIG_0(), true);
  }

  public BVector(long n) {
    this(yarpJNI.new_BVector__SWIG_1(n), true);
  }

  public long size() {
    return yarpJNI.BVector_size(swigCPtr, this);
  }

  public long capacity() {
    return yarpJNI.BVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    yarpJNI.BVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return yarpJNI.BVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    yarpJNI.BVector_clear(swigCPtr, this);
  }

  public void add(boolean x) {
    yarpJNI.BVector_add(swigCPtr, this, x);
  }

  public boolean get(int i) {
    return yarpJNI.BVector_get(swigCPtr, this, i);
  }

  public void set(int i, boolean val) {
    yarpJNI.BVector_set(swigCPtr, this, i, val);
  }

}
