/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class CartesianEvent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CartesianEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CartesianEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_CartesianEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCartesianEventParameters(CartesianEventParameters value) {
    yarpJNI.CartesianEvent_cartesianEventParameters_set(swigCPtr, this, CartesianEventParameters.getCPtr(value), value);
  }

  public CartesianEventParameters getCartesianEventParameters() {
    long cPtr = yarpJNI.CartesianEvent_cartesianEventParameters_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CartesianEventParameters(cPtr, false);
  }

  public void setCartesianEventVariables(CartesianEventVariables value) {
    yarpJNI.CartesianEvent_cartesianEventVariables_set(swigCPtr, this, CartesianEventVariables.getCPtr(value), value);
  }

  public CartesianEventVariables getCartesianEventVariables() {
    long cPtr = yarpJNI.CartesianEvent_cartesianEventVariables_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CartesianEventVariables(cPtr, false);
  }

  public void cartesianEventCallback() {
    yarpJNI.CartesianEvent_cartesianEventCallback(swigCPtr, this);
  }

}
