/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class charArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected charArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(charArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_charArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public charArray(int nelements) {
    this(yarpJNI.new_charArray(nelements), true);
  }

  public short getitem(int index) {
    return yarpJNI.charArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, short value) {
    yarpJNI.charArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_unsigned_char cast() {
    long cPtr = yarpJNI.charArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static charArray frompointer(SWIGTYPE_p_unsigned_char t) {
    long cPtr = yarpJNI.charArray_frompointer(SWIGTYPE_p_unsigned_char.getCPtr(t));
    return (cPtr == 0) ? null : new charArray(cPtr, false);
  }

}
