/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ConnectionWriter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ConnectionWriter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConnectionWriter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_ConnectionWriter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void appendBlock(String data, long len) {
    yarpJNI.ConnectionWriter_appendBlock(swigCPtr, this, data, len);
  }

  public void appendInt(int data) {
    yarpJNI.ConnectionWriter_appendInt(swigCPtr, this, data);
  }

  public void appendInt64(SWIGTYPE_p_YARP_INT64 data) {
    yarpJNI.ConnectionWriter_appendInt64(swigCPtr, this, SWIGTYPE_p_YARP_INT64.getCPtr(data));
  }

  public void appendDouble(double data) {
    yarpJNI.ConnectionWriter_appendDouble(swigCPtr, this, data);
  }

  public void appendString(String str, int terminate) {
    yarpJNI.ConnectionWriter_appendString__SWIG_0(swigCPtr, this, str, terminate);
  }

  public void appendString(String str) {
    yarpJNI.ConnectionWriter_appendString__SWIG_1(swigCPtr, this, str);
  }

  public void appendExternalBlock(String data, long len) {
    yarpJNI.ConnectionWriter_appendExternalBlock(swigCPtr, this, data, len);
  }

  public boolean isTextMode() {
    return yarpJNI.ConnectionWriter_isTextMode(swigCPtr, this);
  }

  public boolean isBareMode() {
    return yarpJNI.ConnectionWriter_isBareMode(swigCPtr, this);
  }

  public void declareSizes(int argc, SWIGTYPE_p_int argv) {
    yarpJNI.ConnectionWriter_declareSizes(swigCPtr, this, argc, SWIGTYPE_p_int.getCPtr(argv));
  }

  public void setReplyHandler(PortReader reader) {
    yarpJNI.ConnectionWriter_setReplyHandler(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public void setReference(Portable obj) {
    yarpJNI.ConnectionWriter_setReference(swigCPtr, this, Portable.getCPtr(obj), obj);
  }

  public boolean convertTextMode() {
    return yarpJNI.ConnectionWriter_convertTextMode(swigCPtr, this);
  }

  public boolean isValid() {
    return yarpJNI.ConnectionWriter_isValid(swigCPtr, this);
  }

  public boolean isActive() {
    return yarpJNI.ConnectionWriter_isActive(swigCPtr, this);
  }

  public boolean isError() {
    return yarpJNI.ConnectionWriter_isError(swigCPtr, this);
  }

  public void requestDrop() {
    yarpJNI.ConnectionWriter_requestDrop(swigCPtr, this);
  }

  public boolean isNull() {
    return yarpJNI.ConnectionWriter_isNull(swigCPtr, this);
  }

  public SWIGTYPE_p_yarp__os__SizedWriter getBuffer() {
    long cPtr = yarpJNI.ConnectionWriter_getBuffer(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_yarp__os__SizedWriter(cPtr, false);
  }

  public void appendRawString(String str) {
    yarpJNI.ConnectionWriter_appendRawString(swigCPtr, this, str);
  }

  public static ConnectionWriter createBufferedConnectionWriter() {
    long cPtr = yarpJNI.ConnectionWriter_createBufferedConnectionWriter();
    return (cPtr == 0) ? null : new ConnectionWriter(cPtr, false);
  }

  public static boolean writeToStream(PortWriter portable, SWIGTYPE_p_yarp__os__OutputStream os) {
    return yarpJNI.ConnectionWriter_writeToStream(PortWriter.getCPtr(portable), portable, SWIGTYPE_p_yarp__os__OutputStream.getCPtr(os));
  }

}
