/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ContactStyle {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ContactStyle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ContactStyle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_ContactStyle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAdmin(boolean value) {
    yarpJNI.ContactStyle_admin_set(swigCPtr, this, value);
  }

  public boolean getAdmin() {
    return yarpJNI.ContactStyle_admin_get(swigCPtr, this);
  }

  public void setQuiet(boolean value) {
    yarpJNI.ContactStyle_quiet_set(swigCPtr, this, value);
  }

  public boolean getQuiet() {
    return yarpJNI.ContactStyle_quiet_get(swigCPtr, this);
  }

  public void setVerboseOnSuccess(boolean value) {
    yarpJNI.ContactStyle_verboseOnSuccess_set(swigCPtr, this, value);
  }

  public boolean getVerboseOnSuccess() {
    return yarpJNI.ContactStyle_verboseOnSuccess_get(swigCPtr, this);
  }

  public void setTimeout(double value) {
    yarpJNI.ContactStyle_timeout_set(swigCPtr, this, value);
  }

  public double getTimeout() {
    return yarpJNI.ContactStyle_timeout_get(swigCPtr, this);
  }

  public void setCarrier(String value) {
    yarpJNI.ContactStyle_carrier_set(swigCPtr, this, value);
  }

  public String getCarrier() {
    return yarpJNI.ContactStyle_carrier_get(swigCPtr, this);
  }

  public void setExpectReply(boolean value) {
    yarpJNI.ContactStyle_expectReply_set(swigCPtr, this, value);
  }

  public boolean getExpectReply() {
    return yarpJNI.ContactStyle_expectReply_get(swigCPtr, this);
  }

  public void setPersistent(boolean value) {
    yarpJNI.ContactStyle_persistent_set(swigCPtr, this, value);
  }

  public boolean getPersistent() {
    return yarpJNI.ContactStyle_persistent_get(swigCPtr, this);
  }

  public void setPersistenceType(ContactStyle.PersistenceType value) {
    yarpJNI.ContactStyle_persistenceType_set(swigCPtr, this, value.swigValue());
  }

  public ContactStyle.PersistenceType getPersistenceType() {
    return ContactStyle.PersistenceType.swigToEnum(yarpJNI.ContactStyle_persistenceType_get(swigCPtr, this));
  }

  public ContactStyle() {
    this(yarpJNI.new_ContactStyle(), true);
  }

  public final static class PersistenceType {
    public final static ContactStyle.PersistenceType OPENENDED = new ContactStyle.PersistenceType("OPENENDED", yarpJNI.ContactStyle_OPENENDED_get());
    public final static ContactStyle.PersistenceType END_WITH_FROM_PORT = new ContactStyle.PersistenceType("END_WITH_FROM_PORT", yarpJNI.ContactStyle_END_WITH_FROM_PORT_get());
    public final static ContactStyle.PersistenceType END_WITH_TO_PORT = new ContactStyle.PersistenceType("END_WITH_TO_PORT", yarpJNI.ContactStyle_END_WITH_TO_PORT_get());
    public final static ContactStyle.PersistenceType NO_PERSISTENCE = new ContactStyle.PersistenceType("NO_PERSISTENCE", yarpJNI.ContactStyle_NO_PERSISTENCE_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static PersistenceType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + PersistenceType.class + " with value " + swigValue);
    }

    private PersistenceType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private PersistenceType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private PersistenceType(String swigName, PersistenceType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static PersistenceType[] swigValues = { OPENENDED, END_WITH_FROM_PORT, END_WITH_TO_PORT, NO_PERSISTENCE };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
