/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Contact {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Contact(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Contact obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Contact(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Contact(String hostName, int port) {
    this(yarpJNI.new_Contact__SWIG_0(hostName, port), true);
  }

  public static Contact empty() {
    return new Contact(yarpJNI.Contact_empty(), true);
  }

  public static Contact invalid() {
    return new Contact(yarpJNI.Contact_invalid(), true);
  }

  public static Contact byName(String name) {
    return new Contact(yarpJNI.Contact_byName(name), true);
  }

  public static Contact byCarrier(String carrier) {
    return new Contact(yarpJNI.Contact_byCarrier(carrier), true);
  }

  public static Contact byConfig(SWIGTYPE_p_Searchable config) {
    return new Contact(yarpJNI.Contact_byConfig(SWIGTYPE_p_Searchable.getCPtr(config)), true);
  }

  public Contact addCarrier(String carrier) {
    return new Contact(yarpJNI.Contact_addCarrier(swigCPtr, this, carrier), true);
  }

  public Contact addHost(String host) {
    return new Contact(yarpJNI.Contact_addHost(swigCPtr, this, host), true);
  }

  public Contact addPort(int portnumber) {
    return new Contact(yarpJNI.Contact_addPort(swigCPtr, this, portnumber), true);
  }

  public static Contact bySocket(String carrier, String host, int portNumber) {
    return new Contact(yarpJNI.Contact_bySocket(carrier, host, portNumber), true);
  }

  public Contact addSocket(String carrier, String host, int portNumber) {
    return new Contact(yarpJNI.Contact_addSocket(swigCPtr, this, carrier, host, portNumber), true);
  }

  public Contact addNested(SWIGTYPE_p_NestedContact nc) {
    return new Contact(yarpJNI.Contact_addNested(swigCPtr, this, SWIGTYPE_p_NestedContact.getCPtr(nc)), true);
  }

  public Contact addName(String name) {
    return new Contact(yarpJNI.Contact_addName(swigCPtr, this, name), true);
  }

  public static String convertHostToIp(String name) {
    return yarpJNI.Contact_convertHostToIp(name);
  }

  public Contact(Contact alt) {
    this(yarpJNI.new_Contact__SWIG_1(Contact.getCPtr(alt), alt), true);
  }

  public String getName() {
    return yarpJNI.Contact_getName(swigCPtr, this);
  }

  public String getHost() {
    return yarpJNI.Contact_getHost(swigCPtr, this);
  }

  public String getCarrier() {
    return yarpJNI.Contact_getCarrier(swigCPtr, this);
  }

  public SWIGTYPE_p_NestedContact getNested() {
    return new SWIGTYPE_p_NestedContact(yarpJNI.Contact_getNested(swigCPtr, this), false);
  }

  public int getPort() {
    return yarpJNI.Contact_getPort(swigCPtr, this);
  }

  public String toString() {
    return yarpJNI.Contact_toString(swigCPtr, this);
  }

  public String toURI() {
    return yarpJNI.Contact_toURI(swigCPtr, this);
  }

  public static Contact fromString(String txt) {
    return new Contact(yarpJNI.Contact_fromString(txt), true);
  }

  public boolean isValid() {
    return yarpJNI.Contact_isValid(swigCPtr, this);
  }

  public Contact() {
    this(yarpJNI.new_Contact__SWIG_2(), true);
  }

  public boolean hasTimeout() {
    return yarpJNI.Contact_hasTimeout(swigCPtr, this);
  }

  public void setTimeout(float timeout) {
    yarpJNI.Contact_setTimeout(swigCPtr, this, timeout);
  }

  public void setNested(SWIGTYPE_p_yarp__os__NestedContact flavor) {
    yarpJNI.Contact_setNested(swigCPtr, this, SWIGTYPE_p_yarp__os__NestedContact.getCPtr(flavor));
  }

  public float getTimeout() {
    return yarpJNI.Contact_getTimeout(swigCPtr, this);
  }

  public String getRegName() {
    return yarpJNI.Contact_getRegName(swigCPtr, this);
  }

  public void setHost(String host) {
    yarpJNI.Contact_setHost(swigCPtr, this, host);
  }

  public void setPort(int port) {
    yarpJNI.Contact_setPort(swigCPtr, this, port);
  }

}
