/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Drivers {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Drivers(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Drivers obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Drivers(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Drivers factory() {
    return new Drivers(yarpJNI.Drivers_factory(), false);
  }

  public DeviceDriver open(String device) {
    long cPtr = yarpJNI.Drivers_open__SWIG_0(swigCPtr, this, device);
    return (cPtr == 0) ? null : new DeviceDriver(cPtr, false);
  }

  public DeviceDriver open(Searchable config) {
    long cPtr = yarpJNI.Drivers_open__SWIG_1(swigCPtr, this, Searchable.getCPtr(config), config);
    return (cPtr == 0) ? null : new DeviceDriver(cPtr, false);
  }

  public String toString_c() {
    return yarpJNI.Drivers_toString_c(swigCPtr, this);
  }

  public void add(DriverCreator creator) {
    yarpJNI.Drivers_add(swigCPtr, this, DriverCreator.getCPtr(creator), creator);
  }

  public DriverCreator find(String name) {
    long cPtr = yarpJNI.Drivers_find(swigCPtr, this, name);
    return (cPtr == 0) ? null : new DriverCreator(cPtr, false);
  }

  public boolean remove(String name) {
    return yarpJNI.Drivers_remove(swigCPtr, this, name);
  }

  public static int yarpdev(int argc, SWIGTYPE_p_p_char argv) {
    return yarpJNI.Drivers_yarpdev(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

}
