/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class DummyConnector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DummyConnector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DummyConnector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_DummyConnector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DummyConnector() {
    this(yarpJNI.new_DummyConnector(), true);
  }

  public void setTextMode(boolean textmode) {
    yarpJNI.DummyConnector_setTextMode(swigCPtr, this, textmode);
  }

  public ConnectionWriter getCleanWriter() {
    return new ConnectionWriter(yarpJNI.DummyConnector_getCleanWriter(swigCPtr, this), false);
  }

  public ConnectionWriter getWriter() {
    return new ConnectionWriter(yarpJNI.DummyConnector_getWriter(swigCPtr, this), false);
  }

  public ConnectionReader getReader() {
    return new ConnectionReader(yarpJNI.DummyConnector_getReader(swigCPtr, this), false);
  }

  public void reset() {
    yarpJNI.DummyConnector_reset(swigCPtr, this);
  }

}
