/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IAudioVisualGrabber {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IAudioVisualGrabber(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IAudioVisualGrabber obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_IAudioVisualGrabber(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean getAudioVisual(ImageRgb image, Sound sound) {
    return yarpJNI.IAudioVisualGrabber_getAudioVisual(swigCPtr, this, ImageRgb.getCPtr(image), image, Sound.getCPtr(sound), sound);
  }

}
