/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IAxisInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IAxisInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IAxisInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_IAxisInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean getAxisName(int axis, SWIGTYPE_p_std__string name) {
    return yarpJNI.IAxisInfo_getAxisName(swigCPtr, this, axis, SWIGTYPE_p_std__string.getCPtr(name));
  }

}
