/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ICartesianControl {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ICartesianControl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ICartesianControl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_ICartesianControl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean setTrackingMode(boolean f) {
    return yarpJNI.ICartesianControl_setTrackingMode(swigCPtr, this, f);
  }

  public boolean getTrackingMode(SWIGTYPE_p_bool f) {
    return yarpJNI.ICartesianControl_getTrackingMode(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(f));
  }

  public boolean setReferenceMode(boolean f) {
    return yarpJNI.ICartesianControl_setReferenceMode(swigCPtr, this, f);
  }

  public boolean getReferenceMode(SWIGTYPE_p_bool f) {
    return yarpJNI.ICartesianControl_getReferenceMode(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(f));
  }

  public boolean setPosePriority(String p) {
    return yarpJNI.ICartesianControl_setPosePriority(swigCPtr, this, p);
  }

  public boolean getPosePriority(SWIGTYPE_p_std__string p) {
    return yarpJNI.ICartesianControl_getPosePriority(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(p));
  }

  public boolean getPose(Vector x, Vector o, Stamp stamp) {
    return yarpJNI.ICartesianControl_getPose__SWIG_0(swigCPtr, this, Vector.getCPtr(x), x, Vector.getCPtr(o), o, Stamp.getCPtr(stamp), stamp);
  }

  public boolean getPose(Vector x, Vector o) {
    return yarpJNI.ICartesianControl_getPose__SWIG_1(swigCPtr, this, Vector.getCPtr(x), x, Vector.getCPtr(o), o);
  }

  public boolean getPose(int axis, Vector x, Vector o, Stamp stamp) {
    return yarpJNI.ICartesianControl_getPose__SWIG_2(swigCPtr, this, axis, Vector.getCPtr(x), x, Vector.getCPtr(o), o, Stamp.getCPtr(stamp), stamp);
  }

  public boolean getPose(int axis, Vector x, Vector o) {
    return yarpJNI.ICartesianControl_getPose__SWIG_3(swigCPtr, this, axis, Vector.getCPtr(x), x, Vector.getCPtr(o), o);
  }

  public boolean goToPose(Vector xd, Vector od, double t) {
    return yarpJNI.ICartesianControl_goToPose__SWIG_0(swigCPtr, this, Vector.getCPtr(xd), xd, Vector.getCPtr(od), od, t);
  }

  public boolean goToPose(Vector xd, Vector od) {
    return yarpJNI.ICartesianControl_goToPose__SWIG_1(swigCPtr, this, Vector.getCPtr(xd), xd, Vector.getCPtr(od), od);
  }

  public boolean goToPosition(Vector xd, double t) {
    return yarpJNI.ICartesianControl_goToPosition__SWIG_0(swigCPtr, this, Vector.getCPtr(xd), xd, t);
  }

  public boolean goToPosition(Vector xd) {
    return yarpJNI.ICartesianControl_goToPosition__SWIG_1(swigCPtr, this, Vector.getCPtr(xd), xd);
  }

  public boolean goToPoseSync(Vector xd, Vector od, double t) {
    return yarpJNI.ICartesianControl_goToPoseSync__SWIG_0(swigCPtr, this, Vector.getCPtr(xd), xd, Vector.getCPtr(od), od, t);
  }

  public boolean goToPoseSync(Vector xd, Vector od) {
    return yarpJNI.ICartesianControl_goToPoseSync__SWIG_1(swigCPtr, this, Vector.getCPtr(xd), xd, Vector.getCPtr(od), od);
  }

  public boolean goToPositionSync(Vector xd, double t) {
    return yarpJNI.ICartesianControl_goToPositionSync__SWIG_0(swigCPtr, this, Vector.getCPtr(xd), xd, t);
  }

  public boolean goToPositionSync(Vector xd) {
    return yarpJNI.ICartesianControl_goToPositionSync__SWIG_1(swigCPtr, this, Vector.getCPtr(xd), xd);
  }

  public boolean getDesired(Vector xdhat, Vector odhat, Vector qdhat) {
    return yarpJNI.ICartesianControl_getDesired(swigCPtr, this, Vector.getCPtr(xdhat), xdhat, Vector.getCPtr(odhat), odhat, Vector.getCPtr(qdhat), qdhat);
  }

  public boolean askForPose(Vector xd, Vector od, Vector xdhat, Vector odhat, Vector qdhat) {
    return yarpJNI.ICartesianControl_askForPose__SWIG_0(swigCPtr, this, Vector.getCPtr(xd), xd, Vector.getCPtr(od), od, Vector.getCPtr(xdhat), xdhat, Vector.getCPtr(odhat), odhat, Vector.getCPtr(qdhat), qdhat);
  }

  public boolean askForPose(Vector q0, Vector xd, Vector od, Vector xdhat, Vector odhat, Vector qdhat) {
    return yarpJNI.ICartesianControl_askForPose__SWIG_1(swigCPtr, this, Vector.getCPtr(q0), q0, Vector.getCPtr(xd), xd, Vector.getCPtr(od), od, Vector.getCPtr(xdhat), xdhat, Vector.getCPtr(odhat), odhat, Vector.getCPtr(qdhat), qdhat);
  }

  public boolean askForPosition(Vector xd, Vector xdhat, Vector odhat, Vector qdhat) {
    return yarpJNI.ICartesianControl_askForPosition__SWIG_0(swigCPtr, this, Vector.getCPtr(xd), xd, Vector.getCPtr(xdhat), xdhat, Vector.getCPtr(odhat), odhat, Vector.getCPtr(qdhat), qdhat);
  }

  public boolean askForPosition(Vector q0, Vector xd, Vector xdhat, Vector odhat, Vector qdhat) {
    return yarpJNI.ICartesianControl_askForPosition__SWIG_1(swigCPtr, this, Vector.getCPtr(q0), q0, Vector.getCPtr(xd), xd, Vector.getCPtr(xdhat), xdhat, Vector.getCPtr(odhat), odhat, Vector.getCPtr(qdhat), qdhat);
  }

  public boolean getDOF(Vector curDof) {
    return yarpJNI.ICartesianControl_getDOF(swigCPtr, this, Vector.getCPtr(curDof), curDof);
  }

  public boolean setDOF(Vector newDof, Vector curDof) {
    return yarpJNI.ICartesianControl_setDOF(swigCPtr, this, Vector.getCPtr(newDof), newDof, Vector.getCPtr(curDof), curDof);
  }

  public boolean getRestPos(Vector curRestPos) {
    return yarpJNI.ICartesianControl_getRestPos(swigCPtr, this, Vector.getCPtr(curRestPos), curRestPos);
  }

  public boolean setRestPos(Vector newRestPos, Vector curRestPos) {
    return yarpJNI.ICartesianControl_setRestPos(swigCPtr, this, Vector.getCPtr(newRestPos), newRestPos, Vector.getCPtr(curRestPos), curRestPos);
  }

  public boolean getRestWeights(Vector curRestWeights) {
    return yarpJNI.ICartesianControl_getRestWeights(swigCPtr, this, Vector.getCPtr(curRestWeights), curRestWeights);
  }

  public boolean setRestWeights(Vector newRestWeights, Vector curRestWeights) {
    return yarpJNI.ICartesianControl_setRestWeights(swigCPtr, this, Vector.getCPtr(newRestWeights), newRestWeights, Vector.getCPtr(curRestWeights), curRestWeights);
  }

  public boolean getLimits(int axis, SWIGTYPE_p_double min, SWIGTYPE_p_double max) {
    return yarpJNI.ICartesianControl_getLimits(swigCPtr, this, axis, SWIGTYPE_p_double.getCPtr(min), SWIGTYPE_p_double.getCPtr(max));
  }

  public boolean setLimits(int axis, double min, double max) {
    return yarpJNI.ICartesianControl_setLimits(swigCPtr, this, axis, min, max);
  }

  public boolean getTrajTime(SWIGTYPE_p_double t) {
    return yarpJNI.ICartesianControl_getTrajTime(swigCPtr, this, SWIGTYPE_p_double.getCPtr(t));
  }

  public boolean setTrajTime(double t) {
    return yarpJNI.ICartesianControl_setTrajTime(swigCPtr, this, t);
  }

  public boolean getInTargetTol(SWIGTYPE_p_double tol) {
    return yarpJNI.ICartesianControl_getInTargetTol(swigCPtr, this, SWIGTYPE_p_double.getCPtr(tol));
  }

  public boolean setInTargetTol(double tol) {
    return yarpJNI.ICartesianControl_setInTargetTol(swigCPtr, this, tol);
  }

  public boolean getJointsVelocities(Vector qdot) {
    return yarpJNI.ICartesianControl_getJointsVelocities(swigCPtr, this, Vector.getCPtr(qdot), qdot);
  }

  public boolean getTaskVelocities(Vector xdot, Vector odot) {
    return yarpJNI.ICartesianControl_getTaskVelocities(swigCPtr, this, Vector.getCPtr(xdot), xdot, Vector.getCPtr(odot), odot);
  }

  public boolean setTaskVelocities(Vector xdot, Vector odot) {
    return yarpJNI.ICartesianControl_setTaskVelocities(swigCPtr, this, Vector.getCPtr(xdot), xdot, Vector.getCPtr(odot), odot);
  }

  public boolean attachTipFrame(Vector x, Vector o) {
    return yarpJNI.ICartesianControl_attachTipFrame(swigCPtr, this, Vector.getCPtr(x), x, Vector.getCPtr(o), o);
  }

  public boolean getTipFrame(Vector x, Vector o) {
    return yarpJNI.ICartesianControl_getTipFrame(swigCPtr, this, Vector.getCPtr(x), x, Vector.getCPtr(o), o);
  }

  public boolean removeTipFrame() {
    return yarpJNI.ICartesianControl_removeTipFrame(swigCPtr, this);
  }

  public boolean checkMotionDone(SWIGTYPE_p_bool f) {
    return yarpJNI.ICartesianControl_checkMotionDone__SWIG_0(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(f));
  }

  public boolean waitMotionDone(double period, double timeout) {
    return yarpJNI.ICartesianControl_waitMotionDone__SWIG_0(swigCPtr, this, period, timeout);
  }

  public boolean waitMotionDone(double period) {
    return yarpJNI.ICartesianControl_waitMotionDone__SWIG_1(swigCPtr, this, period);
  }

  public boolean waitMotionDone() {
    return yarpJNI.ICartesianControl_waitMotionDone__SWIG_2(swigCPtr, this);
  }

  public boolean stopControl() {
    return yarpJNI.ICartesianControl_stopControl(swigCPtr, this);
  }

  public boolean storeContext(SWIGTYPE_p_int id) {
    return yarpJNI.ICartesianControl_storeContext(swigCPtr, this, SWIGTYPE_p_int.getCPtr(id));
  }

  public boolean restoreContext(int id) {
    return yarpJNI.ICartesianControl_restoreContext(swigCPtr, this, id);
  }

  public boolean deleteContext(int id) {
    return yarpJNI.ICartesianControl_deleteContext(swigCPtr, this, id);
  }

  public boolean getInfo(Bottle info) {
    return yarpJNI.ICartesianControl_getInfo(swigCPtr, this, Bottle.getCPtr(info), info);
  }

  public boolean registerEvent(CartesianEvent event) {
    return yarpJNI.ICartesianControl_registerEvent(swigCPtr, this, CartesianEvent.getCPtr(event), event);
  }

  public boolean unregisterEvent(CartesianEvent event) {
    return yarpJNI.ICartesianControl_unregisterEvent(swigCPtr, this, CartesianEvent.getCPtr(event), event);
  }

  public boolean tweakSet(Bottle options) {
    return yarpJNI.ICartesianControl_tweakSet(swigCPtr, this, Bottle.getCPtr(options), options);
  }

  public boolean tweakGet(Bottle options) {
    return yarpJNI.ICartesianControl_tweakGet(swigCPtr, this, Bottle.getCPtr(options), options);
  }

  public boolean checkMotionDone(BVector flag) {
    return yarpJNI.ICartesianControl_checkMotionDone__SWIG_1(swigCPtr, this, BVector.getCPtr(flag), flag);
  }

  public boolean checkMotionDone() {
    return yarpJNI.ICartesianControl_checkMotionDone__SWIG_2(swigCPtr, this);
  }

  public boolean isMotionDone() {
    return yarpJNI.ICartesianControl_isMotionDone(swigCPtr, this);
  }

}
