/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IControlModeRaw {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IControlModeRaw(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IControlModeRaw obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_IControlModeRaw(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean setPositionModeRaw(int j) {
    return yarpJNI.IControlModeRaw_setPositionModeRaw(swigCPtr, this, j);
  }

  public boolean setVelocityModeRaw(int j) {
    return yarpJNI.IControlModeRaw_setVelocityModeRaw(swigCPtr, this, j);
  }

  public boolean setTorqueModeRaw(int j) {
    return yarpJNI.IControlModeRaw_setTorqueModeRaw(swigCPtr, this, j);
  }

  public boolean setImpedancePositionModeRaw(int j) {
    return yarpJNI.IControlModeRaw_setImpedancePositionModeRaw(swigCPtr, this, j);
  }

  public boolean setImpedanceVelocityModeRaw(int j) {
    return yarpJNI.IControlModeRaw_setImpedanceVelocityModeRaw(swigCPtr, this, j);
  }

  public boolean setOpenLoopModeRaw(int j) {
    return yarpJNI.IControlModeRaw_setOpenLoopModeRaw(swigCPtr, this, j);
  }

  public boolean getControlModeRaw(int j, SWIGTYPE_p_int mode) {
    return yarpJNI.IControlModeRaw_getControlModeRaw(swigCPtr, this, j, SWIGTYPE_p_int.getCPtr(mode));
  }

  public boolean getControlModesRaw(SWIGTYPE_p_int modes) {
    return yarpJNI.IControlModeRaw_getControlModesRaw(swigCPtr, this, SWIGTYPE_p_int.getCPtr(modes));
  }

}
