/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IFrameGrabberImageRaw {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IFrameGrabberImageRaw(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IFrameGrabberImageRaw obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_IFrameGrabberImageRaw(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean getImage(ImageMono image) {
    return yarpJNI.IFrameGrabberImageRaw_getImage(swigCPtr, this, ImageMono.getCPtr(image), image);
  }

  public int height() {
    return yarpJNI.IFrameGrabberImageRaw_height(swigCPtr, this);
  }

  public int width() {
    return yarpJNI.IFrameGrabberImageRaw_width(swigCPtr, this);
  }

}
