/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IGazeControl {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IGazeControl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IGazeControl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_IGazeControl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean setTrackingMode(boolean f) {
    return yarpJNI.IGazeControl_setTrackingMode(swigCPtr, this, f);
  }

  public boolean getTrackingMode(SWIGTYPE_p_bool f) {
    return yarpJNI.IGazeControl_getTrackingMode__SWIG_0(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(f));
  }

  public boolean getFixationPoint(Vector fp, Stamp stamp) {
    return yarpJNI.IGazeControl_getFixationPoint__SWIG_0(swigCPtr, this, Vector.getCPtr(fp), fp, Stamp.getCPtr(stamp), stamp);
  }

  public boolean getFixationPoint(Vector fp) {
    return yarpJNI.IGazeControl_getFixationPoint__SWIG_1(swigCPtr, this, Vector.getCPtr(fp), fp);
  }

  public boolean getAngles(Vector ang, Stamp stamp) {
    return yarpJNI.IGazeControl_getAngles__SWIG_0(swigCPtr, this, Vector.getCPtr(ang), ang, Stamp.getCPtr(stamp), stamp);
  }

  public boolean getAngles(Vector ang) {
    return yarpJNI.IGazeControl_getAngles__SWIG_1(swigCPtr, this, Vector.getCPtr(ang), ang);
  }

  public boolean lookAtFixationPoint(Vector fp) {
    return yarpJNI.IGazeControl_lookAtFixationPoint(swigCPtr, this, Vector.getCPtr(fp), fp);
  }

  public boolean lookAtAbsAngles(Vector ang) {
    return yarpJNI.IGazeControl_lookAtAbsAngles(swigCPtr, this, Vector.getCPtr(ang), ang);
  }

  public boolean lookAtRelAngles(Vector ang) {
    return yarpJNI.IGazeControl_lookAtRelAngles(swigCPtr, this, Vector.getCPtr(ang), ang);
  }

  public boolean lookAtMonoPixel(int camSel, Vector px, double z) {
    return yarpJNI.IGazeControl_lookAtMonoPixel__SWIG_0(swigCPtr, this, camSel, Vector.getCPtr(px), px, z);
  }

  public boolean lookAtMonoPixel(int camSel, Vector px) {
    return yarpJNI.IGazeControl_lookAtMonoPixel__SWIG_1(swigCPtr, this, camSel, Vector.getCPtr(px), px);
  }

  public boolean lookAtMonoPixelWithVergence(int camSel, Vector px, double ver) {
    return yarpJNI.IGazeControl_lookAtMonoPixelWithVergence(swigCPtr, this, camSel, Vector.getCPtr(px), px, ver);
  }

  public boolean lookAtStereoPixels(Vector pxl, Vector pxr) {
    return yarpJNI.IGazeControl_lookAtStereoPixels(swigCPtr, this, Vector.getCPtr(pxl), pxl, Vector.getCPtr(pxr), pxr);
  }

  public boolean getNeckTrajTime(SWIGTYPE_p_double t) {
    return yarpJNI.IGazeControl_getNeckTrajTime__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(t));
  }

  public boolean getEyesTrajTime(SWIGTYPE_p_double t) {
    return yarpJNI.IGazeControl_getEyesTrajTime__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(t));
  }

  public boolean getVORGain(SWIGTYPE_p_double gain) {
    return yarpJNI.IGazeControl_getVORGain(swigCPtr, this, SWIGTYPE_p_double.getCPtr(gain));
  }

  public boolean getOCRGain(SWIGTYPE_p_double gain) {
    return yarpJNI.IGazeControl_getOCRGain(swigCPtr, this, SWIGTYPE_p_double.getCPtr(gain));
  }

  public boolean getSaccadesStatus(SWIGTYPE_p_bool f) {
    return yarpJNI.IGazeControl_getSaccadesStatus(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(f));
  }

  public boolean getSaccadesInhibitionPeriod(SWIGTYPE_p_double period) {
    return yarpJNI.IGazeControl_getSaccadesInhibitionPeriod(swigCPtr, this, SWIGTYPE_p_double.getCPtr(period));
  }

  public boolean getSaccadesActivationAngle(SWIGTYPE_p_double angle) {
    return yarpJNI.IGazeControl_getSaccadesActivationAngle(swigCPtr, this, SWIGTYPE_p_double.getCPtr(angle));
  }

  public boolean getLeftEyePose(Vector x, Vector od, Stamp stamp) {
    return yarpJNI.IGazeControl_getLeftEyePose__SWIG_0(swigCPtr, this, Vector.getCPtr(x), x, Vector.getCPtr(od), od, Stamp.getCPtr(stamp), stamp);
  }

  public boolean getLeftEyePose(Vector x, Vector od) {
    return yarpJNI.IGazeControl_getLeftEyePose__SWIG_1(swigCPtr, this, Vector.getCPtr(x), x, Vector.getCPtr(od), od);
  }

  public boolean getRightEyePose(Vector x, Vector od, Stamp stamp) {
    return yarpJNI.IGazeControl_getRightEyePose__SWIG_0(swigCPtr, this, Vector.getCPtr(x), x, Vector.getCPtr(od), od, Stamp.getCPtr(stamp), stamp);
  }

  public boolean getRightEyePose(Vector x, Vector od) {
    return yarpJNI.IGazeControl_getRightEyePose__SWIG_1(swigCPtr, this, Vector.getCPtr(x), x, Vector.getCPtr(od), od);
  }

  public boolean getHeadPose(Vector x, Vector od, Stamp stamp) {
    return yarpJNI.IGazeControl_getHeadPose__SWIG_0(swigCPtr, this, Vector.getCPtr(x), x, Vector.getCPtr(od), od, Stamp.getCPtr(stamp), stamp);
  }

  public boolean getHeadPose(Vector x, Vector od) {
    return yarpJNI.IGazeControl_getHeadPose__SWIG_1(swigCPtr, this, Vector.getCPtr(x), x, Vector.getCPtr(od), od);
  }

  public boolean get2DPixel(int camSel, Vector x, Vector px) {
    return yarpJNI.IGazeControl_get2DPixel(swigCPtr, this, camSel, Vector.getCPtr(x), x, Vector.getCPtr(px), px);
  }

  public boolean get3DPoint(int camSel, Vector px, double z, Vector x) {
    return yarpJNI.IGazeControl_get3DPoint(swigCPtr, this, camSel, Vector.getCPtr(px), px, z, Vector.getCPtr(x), x);
  }

  public boolean get3DPointOnPlane(int camSel, Vector px, Vector plane, Vector x) {
    return yarpJNI.IGazeControl_get3DPointOnPlane(swigCPtr, this, camSel, Vector.getCPtr(px), px, Vector.getCPtr(plane), plane, Vector.getCPtr(x), x);
  }

  public boolean get3DPointFromAngles(int mode, Vector ang, Vector x) {
    return yarpJNI.IGazeControl_get3DPointFromAngles(swigCPtr, this, mode, Vector.getCPtr(ang), ang, Vector.getCPtr(x), x);
  }

  public boolean getAnglesFrom3DPoint(Vector x, Vector ang) {
    return yarpJNI.IGazeControl_getAnglesFrom3DPoint(swigCPtr, this, Vector.getCPtr(x), x, Vector.getCPtr(ang), ang);
  }

  public boolean triangulate3DPoint(Vector pxl, Vector pxr, Vector x) {
    return yarpJNI.IGazeControl_triangulate3DPoint(swigCPtr, this, Vector.getCPtr(pxl), pxl, Vector.getCPtr(pxr), pxr, Vector.getCPtr(x), x);
  }

  public boolean getJointsDesired(Vector qdes) {
    return yarpJNI.IGazeControl_getJointsDesired(swigCPtr, this, Vector.getCPtr(qdes), qdes);
  }

  public boolean getJointsVelocities(Vector qdot) {
    return yarpJNI.IGazeControl_getJointsVelocities(swigCPtr, this, Vector.getCPtr(qdot), qdot);
  }

  public boolean getStereoOptions(Bottle options) {
    return yarpJNI.IGazeControl_getStereoOptions(swigCPtr, this, Bottle.getCPtr(options), options);
  }

  public boolean setNeckTrajTime(double t) {
    return yarpJNI.IGazeControl_setNeckTrajTime(swigCPtr, this, t);
  }

  public boolean setEyesTrajTime(double t) {
    return yarpJNI.IGazeControl_setEyesTrajTime(swigCPtr, this, t);
  }

  public boolean setVORGain(double gain) {
    return yarpJNI.IGazeControl_setVORGain(swigCPtr, this, gain);
  }

  public boolean setOCRGain(double gain) {
    return yarpJNI.IGazeControl_setOCRGain(swigCPtr, this, gain);
  }

  public boolean setSaccadesStatus(boolean f) {
    return yarpJNI.IGazeControl_setSaccadesStatus(swigCPtr, this, f);
  }

  public boolean setSaccadesInhibitionPeriod(double period) {
    return yarpJNI.IGazeControl_setSaccadesInhibitionPeriod(swigCPtr, this, period);
  }

  public boolean setSaccadesActivationAngle(double angle) {
    return yarpJNI.IGazeControl_setSaccadesActivationAngle(swigCPtr, this, angle);
  }

  public boolean setStereoOptions(Bottle options) {
    return yarpJNI.IGazeControl_setStereoOptions(swigCPtr, this, Bottle.getCPtr(options), options);
  }

  public boolean bindNeckPitch(double min, double max) {
    return yarpJNI.IGazeControl_bindNeckPitch(swigCPtr, this, min, max);
  }

  public boolean blockNeckPitch(double val) {
    return yarpJNI.IGazeControl_blockNeckPitch__SWIG_0(swigCPtr, this, val);
  }

  public boolean blockNeckPitch() {
    return yarpJNI.IGazeControl_blockNeckPitch__SWIG_1(swigCPtr, this);
  }

  public boolean bindNeckRoll(double min, double max) {
    return yarpJNI.IGazeControl_bindNeckRoll(swigCPtr, this, min, max);
  }

  public boolean blockNeckRoll(double val) {
    return yarpJNI.IGazeControl_blockNeckRoll__SWIG_0(swigCPtr, this, val);
  }

  public boolean blockNeckRoll() {
    return yarpJNI.IGazeControl_blockNeckRoll__SWIG_1(swigCPtr, this);
  }

  public boolean bindNeckYaw(double min, double max) {
    return yarpJNI.IGazeControl_bindNeckYaw(swigCPtr, this, min, max);
  }

  public boolean blockNeckYaw(double val) {
    return yarpJNI.IGazeControl_blockNeckYaw__SWIG_0(swigCPtr, this, val);
  }

  public boolean blockNeckYaw() {
    return yarpJNI.IGazeControl_blockNeckYaw__SWIG_1(swigCPtr, this);
  }

  public boolean blockEyes(double ver) {
    return yarpJNI.IGazeControl_blockEyes__SWIG_0(swigCPtr, this, ver);
  }

  public boolean blockEyes() {
    return yarpJNI.IGazeControl_blockEyes__SWIG_1(swigCPtr, this);
  }

  public boolean getNeckPitchRange(SWIGTYPE_p_double min, SWIGTYPE_p_double max) {
    return yarpJNI.IGazeControl_getNeckPitchRange(swigCPtr, this, SWIGTYPE_p_double.getCPtr(min), SWIGTYPE_p_double.getCPtr(max));
  }

  public boolean getNeckRollRange(SWIGTYPE_p_double min, SWIGTYPE_p_double max) {
    return yarpJNI.IGazeControl_getNeckRollRange(swigCPtr, this, SWIGTYPE_p_double.getCPtr(min), SWIGTYPE_p_double.getCPtr(max));
  }

  public boolean getNeckYawRange(SWIGTYPE_p_double min, SWIGTYPE_p_double max) {
    return yarpJNI.IGazeControl_getNeckYawRange(swigCPtr, this, SWIGTYPE_p_double.getCPtr(min), SWIGTYPE_p_double.getCPtr(max));
  }

  public boolean getBlockedVergence(SWIGTYPE_p_double ver) {
    return yarpJNI.IGazeControl_getBlockedVergence(swigCPtr, this, SWIGTYPE_p_double.getCPtr(ver));
  }

  public boolean clearNeckPitch() {
    return yarpJNI.IGazeControl_clearNeckPitch(swigCPtr, this);
  }

  public boolean clearNeckRoll() {
    return yarpJNI.IGazeControl_clearNeckRoll(swigCPtr, this);
  }

  public boolean clearNeckYaw() {
    return yarpJNI.IGazeControl_clearNeckYaw(swigCPtr, this);
  }

  public boolean clearEyes() {
    return yarpJNI.IGazeControl_clearEyes(swigCPtr, this);
  }

  public boolean getNeckAngleUserTolerance(SWIGTYPE_p_double angle) {
    return yarpJNI.IGazeControl_getNeckAngleUserTolerance(swigCPtr, this, SWIGTYPE_p_double.getCPtr(angle));
  }

  public boolean setNeckAngleUserTolerance(double angle) {
    return yarpJNI.IGazeControl_setNeckAngleUserTolerance(swigCPtr, this, angle);
  }

  public boolean checkMotionDone(SWIGTYPE_p_bool f) {
    return yarpJNI.IGazeControl_checkMotionDone__SWIG_0(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(f));
  }

  public boolean waitMotionDone(double period, double timeout) {
    return yarpJNI.IGazeControl_waitMotionDone__SWIG_0(swigCPtr, this, period, timeout);
  }

  public boolean waitMotionDone(double period) {
    return yarpJNI.IGazeControl_waitMotionDone__SWIG_1(swigCPtr, this, period);
  }

  public boolean waitMotionDone() {
    return yarpJNI.IGazeControl_waitMotionDone__SWIG_2(swigCPtr, this);
  }

  public boolean checkSaccadeDone(SWIGTYPE_p_bool f) {
    return yarpJNI.IGazeControl_checkSaccadeDone(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(f));
  }

  public boolean waitSaccadeDone(double period, double timeout) {
    return yarpJNI.IGazeControl_waitSaccadeDone__SWIG_0(swigCPtr, this, period, timeout);
  }

  public boolean waitSaccadeDone(double period) {
    return yarpJNI.IGazeControl_waitSaccadeDone__SWIG_1(swigCPtr, this, period);
  }

  public boolean waitSaccadeDone() {
    return yarpJNI.IGazeControl_waitSaccadeDone__SWIG_2(swigCPtr, this);
  }

  public boolean stopControl() {
    return yarpJNI.IGazeControl_stopControl(swigCPtr, this);
  }

  public boolean storeContext(SWIGTYPE_p_int id) {
    return yarpJNI.IGazeControl_storeContext(swigCPtr, this, SWIGTYPE_p_int.getCPtr(id));
  }

  public boolean restoreContext(int id) {
    return yarpJNI.IGazeControl_restoreContext(swigCPtr, this, id);
  }

  public boolean deleteContext(int id) {
    return yarpJNI.IGazeControl_deleteContext(swigCPtr, this, id);
  }

  public boolean getInfo(Bottle info) {
    return yarpJNI.IGazeControl_getInfo(swigCPtr, this, Bottle.getCPtr(info), info);
  }

  public boolean registerEvent(GazeEvent event) {
    return yarpJNI.IGazeControl_registerEvent(swigCPtr, this, GazeEvent.getCPtr(event), event);
  }

  public boolean unregisterEvent(GazeEvent event) {
    return yarpJNI.IGazeControl_unregisterEvent(swigCPtr, this, GazeEvent.getCPtr(event), event);
  }

  public boolean tweakSet(Bottle options) {
    return yarpJNI.IGazeControl_tweakSet(swigCPtr, this, Bottle.getCPtr(options), options);
  }

  public boolean tweakGet(Bottle options) {
    return yarpJNI.IGazeControl_tweakGet(swigCPtr, this, Bottle.getCPtr(options), options);
  }

  public boolean getTrackingMode() {
    return yarpJNI.IGazeControl_getTrackingMode__SWIG_1(swigCPtr, this);
  }

  public double getNeckTrajTime() {
    return yarpJNI.IGazeControl_getNeckTrajTime__SWIG_1(swigCPtr, this);
  }

  public double getEyesTrajTime() {
    return yarpJNI.IGazeControl_getEyesTrajTime__SWIG_1(swigCPtr, this);
  }

  public boolean checkMotionDone() {
    return yarpJNI.IGazeControl_checkMotionDone__SWIG_1(swigCPtr, this);
  }

}
