/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IImpedanceControlRaw {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IImpedanceControlRaw(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImpedanceControlRaw obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_IImpedanceControlRaw(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean getAxes(SWIGTYPE_p_int ax) {
    return yarpJNI.IImpedanceControlRaw_getAxes(swigCPtr, this, SWIGTYPE_p_int.getCPtr(ax));
  }

  public boolean getImpedanceRaw(int j, SWIGTYPE_p_double stiffness, SWIGTYPE_p_double damping) {
    return yarpJNI.IImpedanceControlRaw_getImpedanceRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(stiffness), SWIGTYPE_p_double.getCPtr(damping));
  }

  public boolean setImpedanceRaw(int j, double stiffness, double damping) {
    return yarpJNI.IImpedanceControlRaw_setImpedanceRaw(swigCPtr, this, j, stiffness, damping);
  }

  public boolean setImpedanceOffsetRaw(int j, double offset) {
    return yarpJNI.IImpedanceControlRaw_setImpedanceOffsetRaw(swigCPtr, this, j, offset);
  }

  public boolean getImpedanceOffsetRaw(int j, SWIGTYPE_p_double offset) {
    return yarpJNI.IImpedanceControlRaw_getImpedanceOffsetRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(offset));
  }

  public boolean getCurrentImpedanceLimitRaw(int j, SWIGTYPE_p_double min_stiff, SWIGTYPE_p_double max_stiff, SWIGTYPE_p_double min_damp, SWIGTYPE_p_double max_damp) {
    return yarpJNI.IImpedanceControlRaw_getCurrentImpedanceLimitRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(min_stiff), SWIGTYPE_p_double.getCPtr(max_stiff), SWIGTYPE_p_double.getCPtr(min_damp), SWIGTYPE_p_double.getCPtr(max_damp));
  }

}
