/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ImageMono extends Image {
  private long swigCPtr;

  protected ImageMono(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.ImageMono_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageMono obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_ImageMono(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int getPixelSize() {
    return yarpJNI.ImageMono_getPixelSize(swigCPtr, this);
  }

  public int getPixelCode() {
    return yarpJNI.ImageMono_getPixelCode(swigCPtr, this);
  }

  public SWIGTYPE_p_unsigned_char pixel(int x, int y) {
    return new SWIGTYPE_p_unsigned_char(yarpJNI.ImageMono_pixel(swigCPtr, this, x, y), false);
  }

  public SWIGTYPE_p_unsigned_char access(int x, int y) {
    return new SWIGTYPE_p_unsigned_char(yarpJNI.ImageMono_access(swigCPtr, this, x, y), false);
  }

  public SWIGTYPE_p_unsigned_char safePixel(int x, int y) {
    return new SWIGTYPE_p_unsigned_char(yarpJNI.ImageMono_safePixel__SWIG_0(swigCPtr, this, x, y), false);
  }

  public ImageMono() {
    this(yarpJNI.new_ImageMono(), true);
  }

}
