/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ImageInt extends Image {
  private long swigCPtr;

  protected ImageInt(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.ImageInt_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_ImageInt(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int getPixelSize() {
    return yarpJNI.ImageInt_getPixelSize(swigCPtr, this);
  }

  public int getPixelCode() {
    return yarpJNI.ImageInt_getPixelCode(swigCPtr, this);
  }

  public SWIGTYPE_p_int pixel(int x, int y) {
    return new SWIGTYPE_p_int(yarpJNI.ImageInt_pixel(swigCPtr, this, x, y), false);
  }

  public SWIGTYPE_p_int access(int x, int y) {
    return new SWIGTYPE_p_int(yarpJNI.ImageInt_access(swigCPtr, this, x, y), false);
  }

  public SWIGTYPE_p_int safePixel(int x, int y) {
    return new SWIGTYPE_p_int(yarpJNI.ImageInt_safePixel__SWIG_0(swigCPtr, this, x, y), false);
  }

  public int getPixel(int x, int y) {
    return yarpJNI.ImageInt_getPixel(swigCPtr, this, x, y);
  }

  public void setPixel(int x, int y, int v) {
    yarpJNI.ImageInt_setPixel(swigCPtr, this, x, y, v);
  }

  public ImageInt() {
    this(yarpJNI.new_ImageInt(), true);
  }

}
