/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ImageMono16 extends Image {
  private long swigCPtr;

  protected ImageMono16(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.ImageMono16_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageMono16 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_ImageMono16(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int getPixelSize() {
    return yarpJNI.ImageMono16_getPixelSize(swigCPtr, this);
  }

  public int getPixelCode() {
    return yarpJNI.ImageMono16_getPixelCode(swigCPtr, this);
  }

  public SWIGTYPE_p_yarp__os__NetUint16 pixel(int x, int y) {
    return new SWIGTYPE_p_yarp__os__NetUint16(yarpJNI.ImageMono16_pixel(swigCPtr, this, x, y), false);
  }

  public SWIGTYPE_p_yarp__os__NetUint16 access(int x, int y) {
    return new SWIGTYPE_p_yarp__os__NetUint16(yarpJNI.ImageMono16_access(swigCPtr, this, x, y), false);
  }

  public SWIGTYPE_p_yarp__os__NetUint16 safePixel(int x, int y) {
    return new SWIGTYPE_p_yarp__os__NetUint16(yarpJNI.ImageMono16_safePixel__SWIG_0(swigCPtr, this, x, y), false);
  }

  public ImageMono16() {
    this(yarpJNI.new_ImageMono16(), true);
  }

}
