/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class MotorTorqueParameters {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MotorTorqueParameters(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MotorTorqueParameters obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_MotorTorqueParameters(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBemf(double value) {
    yarpJNI.MotorTorqueParameters_bemf_set(swigCPtr, this, value);
  }

  public double getBemf() {
    return yarpJNI.MotorTorqueParameters_bemf_get(swigCPtr, this);
  }

  public void setBemf_scale(double value) {
    yarpJNI.MotorTorqueParameters_bemf_scale_set(swigCPtr, this, value);
  }

  public double getBemf_scale() {
    return yarpJNI.MotorTorqueParameters_bemf_scale_get(swigCPtr, this);
  }

  public void setKtau(double value) {
    yarpJNI.MotorTorqueParameters_ktau_set(swigCPtr, this, value);
  }

  public double getKtau() {
    return yarpJNI.MotorTorqueParameters_ktau_get(swigCPtr, this);
  }

  public void setKtau_scale(double value) {
    yarpJNI.MotorTorqueParameters_ktau_scale_set(swigCPtr, this, value);
  }

  public double getKtau_scale() {
    return yarpJNI.MotorTorqueParameters_ktau_scale_get(swigCPtr, this);
  }

  public MotorTorqueParameters() {
    this(yarpJNI.new_MotorTorqueParameters(), true);
  }

}
