/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Network extends NetworkBase {
  private long swigCPtr;

  protected Network(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.Network_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Network obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Network(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Network() {
    this(yarpJNI.new_Network(), true);
  }

  public static void init() {
    yarpJNI.Network_init();
  }

  public static void fini() {
    yarpJNI.Network_fini();
  }

}
