/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Pid {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Pid(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Pid obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Pid(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKp(double value) {
    yarpJNI.Pid_kp_set(swigCPtr, this, value);
  }

  public double getKp() {
    return yarpJNI.Pid_kp_get(swigCPtr, this);
  }

  public void setKd(double value) {
    yarpJNI.Pid_kd_set(swigCPtr, this, value);
  }

  public double getKd() {
    return yarpJNI.Pid_kd_get(swigCPtr, this);
  }

  public void setKi(double value) {
    yarpJNI.Pid_ki_set(swigCPtr, this, value);
  }

  public double getKi() {
    return yarpJNI.Pid_ki_get(swigCPtr, this);
  }

  public void setMax_int(double value) {
    yarpJNI.Pid_max_int_set(swigCPtr, this, value);
  }

  public double getMax_int() {
    return yarpJNI.Pid_max_int_get(swigCPtr, this);
  }

  public void setScale(double value) {
    yarpJNI.Pid_scale_set(swigCPtr, this, value);
  }

  public double getScale() {
    return yarpJNI.Pid_scale_get(swigCPtr, this);
  }

  public void setMax_output(double value) {
    yarpJNI.Pid_max_output_set(swigCPtr, this, value);
  }

  public double getMax_output() {
    return yarpJNI.Pid_max_output_get(swigCPtr, this);
  }

  public void setOffset(double value) {
    yarpJNI.Pid_offset_set(swigCPtr, this, value);
  }

  public double getOffset() {
    return yarpJNI.Pid_offset_get(swigCPtr, this);
  }

  public void setStiction_up_val(double value) {
    yarpJNI.Pid_stiction_up_val_set(swigCPtr, this, value);
  }

  public double getStiction_up_val() {
    return yarpJNI.Pid_stiction_up_val_get(swigCPtr, this);
  }

  public void setStiction_down_val(double value) {
    yarpJNI.Pid_stiction_down_val_set(swigCPtr, this, value);
  }

  public double getStiction_down_val() {
    return yarpJNI.Pid_stiction_down_val_get(swigCPtr, this);
  }

  public void setKff(double value) {
    yarpJNI.Pid_kff_set(swigCPtr, this, value);
  }

  public double getKff() {
    return yarpJNI.Pid_kff_get(swigCPtr, this);
  }

  public Pid() {
    this(yarpJNI.new_Pid__SWIG_0(), true);
  }

  public Pid(double kp, double kd, double ki, double int_max, double scale, double out_max) {
    this(yarpJNI.new_Pid__SWIG_1(kp, kd, ki, int_max, scale, out_max), true);
  }

  public Pid(double kp, double kd, double ki, double int_max, double scale, double out_max, double st_up, double st_down, double kff) {
    this(yarpJNI.new_Pid__SWIG_2(kp, kd, ki, int_max, scale, out_max, st_up, st_down, kff), true);
  }

  public void setMaxInt(double m) {
    yarpJNI.Pid_setMaxInt(swigCPtr, this, m);
  }

  public void setMaxOut(double m) {
    yarpJNI.Pid_setMaxOut(swigCPtr, this, m);
  }

  public void setStictionValues(double up_value, double down_value) {
    yarpJNI.Pid_setStictionValues(swigCPtr, this, up_value, down_value);
  }

}
