/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class PortWriter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PortWriter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PortWriter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_PortWriter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean write(ConnectionWriter connection) {
    return yarpJNI.PortWriter_write(swigCPtr, this, ConnectionWriter.getCPtr(connection), connection);
  }

  public void onCompletion() {
    yarpJNI.PortWriter_onCompletion(swigCPtr, this);
  }

  public void onCommencement() {
    yarpJNI.PortWriter_onCommencement(swigCPtr, this);
  }

  public SWIGTYPE_p_Type getWriteType() {
    return new SWIGTYPE_p_Type(yarpJNI.PortWriter_getWriteType(swigCPtr, this), true);
  }

}
