/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class PortReader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PortReader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PortReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_PortReader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    yarpJNI.PortReader_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    yarpJNI.PortReader_change_ownership(this, swigCPtr, true);
  }

  public boolean read(ConnectionReader connection) {
    return yarpJNI.PortReader_read(swigCPtr, this, ConnectionReader.getCPtr(connection), connection);
  }

  public SWIGTYPE_p_Type getReadType() {
    return new SWIGTYPE_p_Type((getClass() == PortReader.class) ? yarpJNI.PortReader_getReadType(swigCPtr, this) : yarpJNI.PortReader_getReadTypeSwigExplicitPortReader(swigCPtr, this), true);
  }

  public PortReader() {
    this(yarpJNI.new_PortReader(), true);
    yarpJNI.PortReader_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
