/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class PortablePairBase extends Portable {
  private long swigCPtr;

  protected PortablePairBase(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.PortablePairBase_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PortablePairBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_PortablePairBase(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static boolean readPair(ConnectionReader connection, Portable head, Portable body) {
    return yarpJNI.PortablePairBase_readPair(ConnectionReader.getCPtr(connection), connection, Portable.getCPtr(head), head, Portable.getCPtr(body), body);
  }

  public static boolean writePair(ConnectionWriter connection, Portable head, Portable body) {
    return yarpJNI.PortablePairBase_writePair(ConnectionWriter.getCPtr(connection), connection, Portable.getCPtr(head), head, Portable.getCPtr(body), body);
  }

}
