/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ResourceFinder extends Searchable {
  private long swigCPtr;

  protected ResourceFinder(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.ResourceFinder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ResourceFinder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_ResourceFinder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ResourceFinder() {
    this(yarpJNI.new_ResourceFinder__SWIG_0(), true);
  }

  public ResourceFinder(ResourceFinder alt) {
    this(yarpJNI.new_ResourceFinder__SWIG_1(ResourceFinder.getCPtr(alt), alt), true);
  }

  public boolean setVerbose(boolean verbose) {
    return yarpJNI.ResourceFinder_setVerbose__SWIG_0(swigCPtr, this, verbose);
  }

  public boolean setVerbose() {
    return yarpJNI.ResourceFinder_setVerbose__SWIG_1(swigCPtr, this);
  }

  public boolean setQuiet(boolean quiet) {
    return yarpJNI.ResourceFinder_setQuiet__SWIG_0(swigCPtr, this, quiet);
  }

  public boolean setQuiet() {
    return yarpJNI.ResourceFinder_setQuiet__SWIG_1(swigCPtr, this);
  }

  public boolean configure(String policyName, int argc, SWIGTYPE_p_p_char argv, boolean skipFirstArgument) {
    return yarpJNI.ResourceFinder_configure__SWIG_0(swigCPtr, this, policyName, argc, SWIGTYPE_p_p_char.getCPtr(argv), skipFirstArgument);
  }

  public boolean configure(String policyName, int argc, SWIGTYPE_p_p_char argv) {
    return yarpJNI.ResourceFinder_configure__SWIG_1(swigCPtr, this, policyName, argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public boolean configure(int argc, SWIGTYPE_p_p_char argv) {
    return yarpJNI.ResourceFinder_configure__SWIG_2(swigCPtr, this, argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public boolean setDefaultContext(String contextName) {
    return yarpJNI.ResourceFinder_setDefaultContext(swigCPtr, this, contextName);
  }

  public boolean setContext(String contextName) {
    return yarpJNI.ResourceFinder_setContext(swigCPtr, this, contextName);
  }

  public boolean setDefault(String key, String val) {
    return yarpJNI.ResourceFinder_setDefault__SWIG_0(swigCPtr, this, key, val);
  }

  public boolean setDefault(String key, Value val) {
    return yarpJNI.ResourceFinder_setDefault__SWIG_1(swigCPtr, this, key, Value.getCPtr(val), val);
  }

  public boolean setDefaultConfigFile(String fname) {
    return yarpJNI.ResourceFinder_setDefaultConfigFile(swigCPtr, this, fname);
  }

  public String findFile(String key) {
    return yarpJNI.ResourceFinder_findFile__SWIG_0(swigCPtr, this, key);
  }

  public String findFileByName(String fileName) {
    return yarpJNI.ResourceFinder_findFileByName__SWIG_0(swigCPtr, this, fileName);
  }

  public String findPath(String key) {
    return yarpJNI.ResourceFinder_findPath__SWIG_0(swigCPtr, this, key);
  }

  public Bottle findPaths(String key) {
    return new Bottle(yarpJNI.ResourceFinder_findPaths__SWIG_0(swigCPtr, this, key), true);
  }

  public String findPath() {
    return yarpJNI.ResourceFinder_findPath__SWIG_1(swigCPtr, this);
  }

  public String getContext() {
    return yarpJNI.ResourceFinder_getContext(swigCPtr, this);
  }

  public String getContextPath() {
    return yarpJNI.ResourceFinder_getContextPath(swigCPtr, this);
  }

  public Bottle getContexts() {
    return new Bottle(yarpJNI.ResourceFinder_getContexts(swigCPtr, this), true);
  }

  public boolean check(String key) {
    return yarpJNI.ResourceFinder_check__SWIG_0(swigCPtr, this, key);
  }

  public Value find(String key) {
    return new Value(yarpJNI.ResourceFinder_find(swigCPtr, this, key), false);
  }

  public Bottle findGroup(String key) {
    return new Bottle(yarpJNI.ResourceFinder_findGroup__SWIG_0(swigCPtr, this, key), false);
  }

  public boolean isNull() {
    return yarpJNI.ResourceFinder_isNull(swigCPtr, this);
  }

  public String toString() {
    return yarpJNI.ResourceFinder_toString(swigCPtr, this);
  }

  public ResourceFinder findNestedResourceFinder(String key) {
    return new ResourceFinder(yarpJNI.ResourceFinder_findNestedResourceFinder(swigCPtr, this, key), true);
  }

  public boolean isConfigured() {
    return yarpJNI.ResourceFinder_isConfigured(swigCPtr, this);
  }

  public static ResourceFinder getResourceFinderSingleton() {
    return new ResourceFinder(yarpJNI.ResourceFinder_getResourceFinderSingleton(), false);
  }

  public boolean check(String key, String comment) {
    return yarpJNI.ResourceFinder_check__SWIG_1_0(swigCPtr, this, key, comment);
  }

  public Value check(String key, Value fallback, String comment) {
    return new Value(yarpJNI.ResourceFinder_check__SWIG_1_1(swigCPtr, this, key, Value.getCPtr(fallback), fallback, comment), true);
  }

  public Value check(String key, Value fallback) {
    return new Value(yarpJNI.ResourceFinder_check__SWIG_1_2(swigCPtr, this, key, Value.getCPtr(fallback), fallback), true);
  }

  public Bottle findGroup(String key, String comment) {
    return new Bottle(yarpJNI.ResourceFinder_findGroup__SWIG_1_0(swigCPtr, this, key, comment), false);
  }

  public static String getDataHome() {
    return yarpJNI.ResourceFinder_getDataHome();
  }

  public static String getDataHomeNoCreate() {
    return yarpJNI.ResourceFinder_getDataHomeNoCreate();
  }

  public static String getConfigHome() {
    return yarpJNI.ResourceFinder_getConfigHome();
  }

  public static String getConfigHomeNoCreate() {
    return yarpJNI.ResourceFinder_getConfigHomeNoCreate();
  }

  public String getHomeContextPath() {
    return yarpJNI.ResourceFinder_getHomeContextPath(swigCPtr, this);
  }

  public String getHomeRobotPath() {
    return yarpJNI.ResourceFinder_getHomeRobotPath(swigCPtr, this);
  }

  public static Bottle getDataDirs() {
    return new Bottle(yarpJNI.ResourceFinder_getDataDirs(), true);
  }

  public static Bottle getConfigDirs() {
    return new Bottle(yarpJNI.ResourceFinder_getConfigDirs(), true);
  }

  public Bottle findPaths(String key, SWIGTYPE_p_ResourceFinderOptions options) {
    return new Bottle(yarpJNI.ResourceFinder_findPaths__SWIG_1(swigCPtr, this, key, SWIGTYPE_p_ResourceFinderOptions.getCPtr(options)), true);
  }

  public String findPath(String key, SWIGTYPE_p_ResourceFinderOptions options) {
    return yarpJNI.ResourceFinder_findPath__SWIG_2(swigCPtr, this, key, SWIGTYPE_p_ResourceFinderOptions.getCPtr(options));
  }

  public String findFile(String key, SWIGTYPE_p_ResourceFinderOptions options) {
    return yarpJNI.ResourceFinder_findFile__SWIG_1(swigCPtr, this, key, SWIGTYPE_p_ResourceFinderOptions.getCPtr(options));
  }

  public String findFileByName(String fileName, SWIGTYPE_p_ResourceFinderOptions options) {
    return yarpJNI.ResourceFinder_findFileByName__SWIG_1(swigCPtr, this, fileName, SWIGTYPE_p_ResourceFinderOptions.getCPtr(options));
  }

  public boolean readConfig(Property config, String key, SWIGTYPE_p_ResourceFinderOptions options) {
    return yarpJNI.ResourceFinder_readConfig(swigCPtr, this, Property.getCPtr(config), config, key, SWIGTYPE_p_ResourceFinderOptions.getCPtr(options));
  }

  public boolean configure(String policyName, SVector argv, boolean skipFirstArgument) {
    return yarpJNI.ResourceFinder_configure__SWIG_3(swigCPtr, this, policyName, SVector.getCPtr(argv), argv, skipFirstArgument);
  }

  public boolean configure(String policyName, SVector argv) {
    return yarpJNI.ResourceFinder_configure__SWIG_4(swigCPtr, this, policyName, SVector.getCPtr(argv), argv);
  }

}
