/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class RFModule {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RFModule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RFModule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_RFModule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    yarpJNI.RFModule_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    yarpJNI.RFModule_change_ownership(this, swigCPtr, true);
  }

  public RFModule() {
    this(yarpJNI.new_RFModule(), true);
    yarpJNI.RFModule_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public double getPeriod() {
    return (getClass() == RFModule.class) ? yarpJNI.RFModule_getPeriod(swigCPtr, this) : yarpJNI.RFModule_getPeriodSwigExplicitRFModule(swigCPtr, this);
  }

  public boolean updateModule() {
    return yarpJNI.RFModule_updateModule(swigCPtr, this);
  }

  public int runModule() {
    return (getClass() == RFModule.class) ? yarpJNI.RFModule_runModule__SWIG_0(swigCPtr, this) : yarpJNI.RFModule_runModuleSwigExplicitRFModule__SWIG_0(swigCPtr, this);
  }

  public int runModule(ResourceFinder rf) {
    return (getClass() == RFModule.class) ? yarpJNI.RFModule_runModule__SWIG_1(swigCPtr, this, ResourceFinder.getCPtr(rf), rf) : yarpJNI.RFModule_runModuleSwigExplicitRFModule__SWIG_1(swigCPtr, this, ResourceFinder.getCPtr(rf), rf);
  }

  public boolean configure(ResourceFinder rf) {
    return (getClass() == RFModule.class) ? yarpJNI.RFModule_configure(swigCPtr, this, ResourceFinder.getCPtr(rf), rf) : yarpJNI.RFModule_configureSwigExplicitRFModule(swigCPtr, this, ResourceFinder.getCPtr(rf), rf);
  }

  public boolean respond(Bottle command, Bottle reply) {
    return (getClass() == RFModule.class) ? yarpJNI.RFModule_respond(swigCPtr, this, Bottle.getCPtr(command), command, Bottle.getCPtr(reply), reply) : yarpJNI.RFModule_respondSwigExplicitRFModule(swigCPtr, this, Bottle.getCPtr(command), command, Bottle.getCPtr(reply), reply);
  }

  public boolean attach(Port source) {
    return (getClass() == RFModule.class) ? yarpJNI.RFModule_attach(swigCPtr, this, Port.getCPtr(source), source) : yarpJNI.RFModule_attachSwigExplicitRFModule(swigCPtr, this, Port.getCPtr(source), source);
  }

  public boolean attach_rpc_server(RpcServer source) {
    return (getClass() == RFModule.class) ? yarpJNI.RFModule_attach_rpc_server(swigCPtr, this, RpcServer.getCPtr(source), source) : yarpJNI.RFModule_attach_rpc_serverSwigExplicitRFModule(swigCPtr, this, RpcServer.getCPtr(source), source);
  }

  public boolean attachTerminal() {
    return yarpJNI.RFModule_attachTerminal(swigCPtr, this);
  }

  public boolean detachTerminal() {
    return yarpJNI.RFModule_detachTerminal(swigCPtr, this);
  }

  public boolean interruptModule() {
    return (getClass() == RFModule.class) ? yarpJNI.RFModule_interruptModule(swigCPtr, this) : yarpJNI.RFModule_interruptModuleSwigExplicitRFModule(swigCPtr, this);
  }

  public boolean close() {
    return (getClass() == RFModule.class) ? yarpJNI.RFModule_close(swigCPtr, this) : yarpJNI.RFModule_closeSwigExplicitRFModule(swigCPtr, this);
  }

  public void stopModule(boolean wait) {
    yarpJNI.RFModule_stopModule__SWIG_0(swigCPtr, this, wait);
  }

  public void stopModule() {
    yarpJNI.RFModule_stopModule__SWIG_1(swigCPtr, this);
  }

  public boolean isStopping() {
    return yarpJNI.RFModule_isStopping(swigCPtr, this);
  }

  public String getName(String subName) {
    return yarpJNI.RFModule_getName__SWIG_0(swigCPtr, this, subName);
  }

  public String getName() {
    return yarpJNI.RFModule_getName__SWIG_1(swigCPtr, this);
  }

  public void setName(String name) {
    yarpJNI.RFModule_setName(swigCPtr, this, name);
  }

  public boolean safeRespond(Bottle command, Bottle reply) {
    return yarpJNI.RFModule_safeRespond(swigCPtr, this, Bottle.getCPtr(command), command, Bottle.getCPtr(reply), reply);
  }

}
