/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class RpcClient extends AbstractContactable {
  private long swigCPtr;

  protected RpcClient(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.RpcClient_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RpcClient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_RpcClient(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RpcClient() {
    this(yarpJNI.new_RpcClient(), true);
  }

  public boolean read(PortReader reader, boolean willReply) {
    return yarpJNI.RpcClient_read__SWIG_0(swigCPtr, this, PortReader.getCPtr(reader), reader, willReply);
  }

  public boolean read(PortReader reader) {
    return yarpJNI.RpcClient_read__SWIG_1(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public boolean reply(PortWriter writer) {
    return yarpJNI.RpcClient_reply(swigCPtr, this, PortWriter.getCPtr(writer), writer);
  }

  public boolean replyAndDrop(PortWriter writer) {
    return yarpJNI.RpcClient_replyAndDrop(swigCPtr, this, PortWriter.getCPtr(writer), writer);
  }

  public void setInputMode(boolean expectInput) {
    yarpJNI.RpcClient_setInputMode(swigCPtr, this, expectInput);
  }

  public void setOutputMode(boolean expectOutput) {
    yarpJNI.RpcClient_setOutputMode(swigCPtr, this, expectOutput);
  }

  public void setRpcMode(boolean expectRpc) {
    yarpJNI.RpcClient_setRpcMode(swigCPtr, this, expectRpc);
  }

  public Port asPort() {
    return new Port(yarpJNI.RpcClient_asPort__SWIG_0(swigCPtr, this), false);
  }

  public boolean write(Bottle data1, Bottle data2) {
    return yarpJNI.RpcClient_write(swigCPtr, this, Bottle.getCPtr(data1), data1, Bottle.getCPtr(data2), data2);
  }

}
