/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class RpcServer extends AbstractContactable {
  private long swigCPtr;

  protected RpcServer(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.RpcServer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RpcServer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_RpcServer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean open() {
    return yarpJNI.RpcServer_open_SWIG_0_0(swigCPtr, this);
  }

  public boolean open(String name) {
    return yarpJNI.RpcServer_open_SWIG_0_1(swigCPtr, this, name);
  }

  public boolean open(Contact contact, boolean registerName) {
    return yarpJNI.RpcServer_open_SWIG_0_2(swigCPtr, this, Contact.getCPtr(contact), contact, registerName);
  }

  public boolean open(Contact contact) {
    return yarpJNI.RpcServer_open_SWIG_0_3(swigCPtr, this, Contact.getCPtr(contact), contact);
  }

  public RpcServer() {
    this(yarpJNI.new_RpcServer(), true);
  }

  public boolean write(PortWriter writer, PortWriter callback) {
    return yarpJNI.RpcServer_write__SWIG_0(swigCPtr, this, PortWriter.getCPtr(writer), writer, PortWriter.getCPtr(callback), callback);
  }

  public boolean write(PortWriter writer) {
    return yarpJNI.RpcServer_write__SWIG_1(swigCPtr, this, PortWriter.getCPtr(writer), writer);
  }

  public boolean write(PortWriter writer, PortReader reader, PortWriter callback) {
    return yarpJNI.RpcServer_write__SWIG_2(swigCPtr, this, PortWriter.getCPtr(writer), writer, PortReader.getCPtr(reader), reader, PortWriter.getCPtr(callback), callback);
  }

  public boolean write(PortWriter writer, PortReader reader) {
    return yarpJNI.RpcServer_write__SWIG_3(swigCPtr, this, PortWriter.getCPtr(writer), writer, PortReader.getCPtr(reader), reader);
  }

  public boolean read(PortReader reader, boolean willReply) {
    return yarpJNI.RpcServer_read__SWIG_0(swigCPtr, this, PortReader.getCPtr(reader), reader, willReply);
  }

  public boolean read(PortReader reader) {
    return yarpJNI.RpcServer_read__SWIG_1(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public void setInputMode(boolean expectInput) {
    yarpJNI.RpcServer_setInputMode(swigCPtr, this, expectInput);
  }

  public void setOutputMode(boolean expectOutput) {
    yarpJNI.RpcServer_setOutputMode(swigCPtr, this, expectOutput);
  }

  public void setRpcMode(boolean expectRpc) {
    yarpJNI.RpcServer_setRpcMode(swigCPtr, this, expectRpc);
  }

  public Port asPort() {
    return new Port(yarpJNI.RpcServer_asPort__SWIG_0(swigCPtr, this), false);
  }

}
