/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Semaphore {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Semaphore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Semaphore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Semaphore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Semaphore(long initialCount) {
    this(yarpJNI.new_Semaphore__SWIG_0(initialCount), true);
  }

  public Semaphore() {
    this(yarpJNI.new_Semaphore__SWIG_1(), true);
  }

  public void wait_c() {
    yarpJNI.Semaphore_wait_c(swigCPtr, this);
  }

  public boolean waitWithTimeout(double timeoutInSeconds) {
    return yarpJNI.Semaphore_waitWithTimeout(swigCPtr, this, timeoutInSeconds);
  }

  public boolean check() {
    return yarpJNI.Semaphore_check(swigCPtr, this);
  }

  public void post() {
    yarpJNI.Semaphore_post(swigCPtr, this);
  }

}
