/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class SWIGTYPE_p_yarp__os__OutputStream {
  private long swigCPtr;

  protected SWIGTYPE_p_yarp__os__OutputStream(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_yarp__os__OutputStream() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_yarp__os__OutputStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

