/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Things {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Things(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Things obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Things(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Things() {
    this(yarpJNI.new_Things(), true);
  }

  public void setPortWriter(PortWriter writer) {
    yarpJNI.Things_setPortWriter(swigCPtr, this, PortWriter.getCPtr(writer), writer);
  }

  public PortWriter getPortWriter() {
    long cPtr = yarpJNI.Things_getPortWriter(swigCPtr, this);
    return (cPtr == 0) ? null : new PortWriter(cPtr, false);
  }

  public boolean setConnectionReader(ConnectionReader reader) {
    return yarpJNI.Things_setConnectionReader(swigCPtr, this, ConnectionReader.getCPtr(reader), reader);
  }

  public boolean write(ConnectionWriter connection) {
    return yarpJNI.Things_write(swigCPtr, this, ConnectionWriter.getCPtr(connection), connection);
  }

  public void reset() {
    yarpJNI.Things_reset(swigCPtr, this);
  }

  public boolean hasBeenRead() {
    return yarpJNI.Things_hasBeenRead(swigCPtr, this);
  }

  public Value asValue() {
    long cPtr = yarpJNI.Things_asValue(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public Bottle asBottle() {
    long cPtr = yarpJNI.Things_asBottle(swigCPtr, this);
    return (cPtr == 0) ? null : new Bottle(cPtr, false);
  }

  public Property asProperty() {
    long cPtr = yarpJNI.Things_asProperty(swigCPtr, this);
    return (cPtr == 0) ? null : new Property(cPtr, false);
  }

  public Vector asVector() {
    long cPtr = yarpJNI.Things_asVector(swigCPtr, this);
    return (cPtr == 0) ? null : new Vector(cPtr, false);
  }

  public SWIGTYPE_p_yarp__sig__Matrix asMatrix() {
    long cPtr = yarpJNI.Things_asMatrix(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_yarp__sig__Matrix(cPtr, false);
  }

  public Image asImage() {
    long cPtr = yarpJNI.Things_asImage(swigCPtr, this);
    return (cPtr == 0) ? null : new Image(cPtr, false);
  }

  public ImageRgb asImageOfPixelRgb() {
    long cPtr = yarpJNI.Things_asImageOfPixelRgb(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageRgb(cPtr, false);
  }

  public SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t asImageOfPixelBgr() {
    long cPtr = yarpJNI.Things_asImageOfPixelBgr(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t(cPtr, false);
  }

  public ImageMono asImageOfPixelMono() {
    long cPtr = yarpJNI.Things_asImageOfPixelMono(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageMono(cPtr, false);
  }

}
