/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class TypedReaderCallbackImageRgba {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TypedReaderCallbackImageRgba(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypedReaderCallbackImageRgba obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_TypedReaderCallbackImageRgba(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void onRead(ImageRgba datum) {
    yarpJNI.TypedReaderCallbackImageRgba_onRead__SWIG_0(swigCPtr, this, ImageRgba.getCPtr(datum), datum);
  }

  public void onRead(ImageRgba datum, TypedReaderImageRgba reader) {
    yarpJNI.TypedReaderCallbackImageRgba_onRead__SWIG_1(swigCPtr, this, ImageRgba.getCPtr(datum), datum, TypedReaderImageRgba.getCPtr(reader), reader);
  }

  public TypedReaderCallbackImageRgba() {
    this(yarpJNI.new_TypedReaderCallbackImageRgba(), true);
  }

}
