/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class TypedReaderCallbackImageMono16 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TypedReaderCallbackImageMono16(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypedReaderCallbackImageMono16 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_TypedReaderCallbackImageMono16(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void onRead(ImageMono16 datum) {
    yarpJNI.TypedReaderCallbackImageMono16_onRead__SWIG_0(swigCPtr, this, ImageMono16.getCPtr(datum), datum);
  }

  public void onRead(ImageMono16 datum, TypedReaderImageMono16 reader) {
    yarpJNI.TypedReaderCallbackImageMono16_onRead__SWIG_1(swigCPtr, this, ImageMono16.getCPtr(datum), datum, TypedReaderImageMono16.getCPtr(reader), reader);
  }

  public TypedReaderCallbackImageMono16() {
    this(yarpJNI.new_TypedReaderCallbackImageMono16(), true);
  }

}
