/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class TypedReaderImageRgba {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TypedReaderImageRgba(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypedReaderImageRgba obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_TypedReaderImageRgba(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStrict(boolean strict) {
    yarpJNI.TypedReaderImageRgba_setStrict__SWIG_0(swigCPtr, this, strict);
  }

  public void setStrict() {
    yarpJNI.TypedReaderImageRgba_setStrict__SWIG_1(swigCPtr, this);
  }

  public ImageRgba read(boolean shouldWait) {
    long cPtr = yarpJNI.TypedReaderImageRgba_read__SWIG_0(swigCPtr, this, shouldWait);
    return (cPtr == 0) ? null : new ImageRgba(cPtr, false);
  }

  public ImageRgba read() {
    long cPtr = yarpJNI.TypedReaderImageRgba_read__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageRgba(cPtr, false);
  }

  public void interrupt() {
    yarpJNI.TypedReaderImageRgba_interrupt(swigCPtr, this);
  }

  public ImageRgba lastRead() {
    long cPtr = yarpJNI.TypedReaderImageRgba_lastRead(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageRgba(cPtr, false);
  }

  public boolean isClosed() {
    return yarpJNI.TypedReaderImageRgba_isClosed(swigCPtr, this);
  }

  public void useCallback(TypedReaderCallbackImageRgba callback) {
    yarpJNI.TypedReaderImageRgba_useCallback(swigCPtr, this, TypedReaderCallbackImageRgba.getCPtr(callback), callback);
  }

  public void disableCallback() {
    yarpJNI.TypedReaderImageRgba_disableCallback(swigCPtr, this);
  }

  public int getPendingReads() {
    return yarpJNI.TypedReaderImageRgba_getPendingReads(swigCPtr, this);
  }

  public String getName() {
    return yarpJNI.TypedReaderImageRgba_getName(swigCPtr, this);
  }

  public void setReplier(PortReader reader) {
    yarpJNI.TypedReaderImageRgba_setReplier(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public SWIGTYPE_p_void acquire() {
    long cPtr = yarpJNI.TypedReaderImageRgba_acquire(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void release(SWIGTYPE_p_void handle) {
    yarpJNI.TypedReaderImageRgba_release(swigCPtr, this, SWIGTYPE_p_void.getCPtr(handle));
  }

  public void setTargetPeriod(double period) {
    yarpJNI.TypedReaderImageRgba_setTargetPeriod(swigCPtr, this, period);
  }

}
