/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class TypedReaderCallbackImageInt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TypedReaderCallbackImageInt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypedReaderCallbackImageInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_TypedReaderCallbackImageInt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void onRead(ImageInt datum) {
    yarpJNI.TypedReaderCallbackImageInt_onRead__SWIG_0(swigCPtr, this, ImageInt.getCPtr(datum), datum);
  }

  public void onRead(ImageInt datum, TypedReaderImageInt reader) {
    yarpJNI.TypedReaderCallbackImageInt_onRead__SWIG_1(swigCPtr, this, ImageInt.getCPtr(datum), datum, TypedReaderImageInt.getCPtr(reader), reader);
  }

  public TypedReaderCallbackImageInt() {
    this(yarpJNI.new_TypedReaderCallbackImageInt(), true);
  }

}
