/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class TypedReaderImageMono16 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TypedReaderImageMono16(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypedReaderImageMono16 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_TypedReaderImageMono16(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStrict(boolean strict) {
    yarpJNI.TypedReaderImageMono16_setStrict__SWIG_0(swigCPtr, this, strict);
  }

  public void setStrict() {
    yarpJNI.TypedReaderImageMono16_setStrict__SWIG_1(swigCPtr, this);
  }

  public ImageMono16 read(boolean shouldWait) {
    long cPtr = yarpJNI.TypedReaderImageMono16_read__SWIG_0(swigCPtr, this, shouldWait);
    return (cPtr == 0) ? null : new ImageMono16(cPtr, false);
  }

  public ImageMono16 read() {
    long cPtr = yarpJNI.TypedReaderImageMono16_read__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageMono16(cPtr, false);
  }

  public void interrupt() {
    yarpJNI.TypedReaderImageMono16_interrupt(swigCPtr, this);
  }

  public ImageMono16 lastRead() {
    long cPtr = yarpJNI.TypedReaderImageMono16_lastRead(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageMono16(cPtr, false);
  }

  public boolean isClosed() {
    return yarpJNI.TypedReaderImageMono16_isClosed(swigCPtr, this);
  }

  public void useCallback(TypedReaderCallbackImageMono16 callback) {
    yarpJNI.TypedReaderImageMono16_useCallback(swigCPtr, this, TypedReaderCallbackImageMono16.getCPtr(callback), callback);
  }

  public void disableCallback() {
    yarpJNI.TypedReaderImageMono16_disableCallback(swigCPtr, this);
  }

  public int getPendingReads() {
    return yarpJNI.TypedReaderImageMono16_getPendingReads(swigCPtr, this);
  }

  public String getName() {
    return yarpJNI.TypedReaderImageMono16_getName(swigCPtr, this);
  }

  public void setReplier(PortReader reader) {
    yarpJNI.TypedReaderImageMono16_setReplier(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public SWIGTYPE_p_void acquire() {
    long cPtr = yarpJNI.TypedReaderImageMono16_acquire(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void release(SWIGTYPE_p_void handle) {
    yarpJNI.TypedReaderImageMono16_release(swigCPtr, this, SWIGTYPE_p_void.getCPtr(handle));
  }

  public void setTargetPeriod(double period) {
    yarpJNI.TypedReaderImageMono16_setTargetPeriod(swigCPtr, this, period);
  }

}
