/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Value extends Portable {
  private long swigCPtr;

  protected Value(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.Value_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Value obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Value(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean check(String key) {
    return yarpJNI.Value_check__SWIG_0_0(swigCPtr, this, key);
  }

  public boolean check(String key, String comment) {
    return yarpJNI.Value_check__SWIG_0_1(swigCPtr, this, key, comment);
  }

  public Value check(String key, Value fallback, String comment) {
    return new Value(yarpJNI.Value_check__SWIG_0_2(swigCPtr, this, key, Value.getCPtr(fallback), fallback, comment), true);
  }

  public Value check(String key, Value fallback) {
    return new Value(yarpJNI.Value_check__SWIG_0_3(swigCPtr, this, key, Value.getCPtr(fallback), fallback), true);
  }

  public Bottle findGroup(String key) {
    return new Bottle(yarpJNI.Value_findGroup__SWIG_0_0(swigCPtr, this, key), false);
  }

  public Bottle findGroup(String key, String comment) {
    return new Bottle(yarpJNI.Value_findGroup__SWIG_0_1(swigCPtr, this, key, comment), false);
  }

  public Value() {
    this(yarpJNI.new_Value__SWIG_0(), true);
  }

  public Value(int x, boolean isVocab) {
    this(yarpJNI.new_Value__SWIG_1(x, isVocab), true);
  }

  public Value(int x) {
    this(yarpJNI.new_Value__SWIG_2(x), true);
  }

  public Value(double x) {
    this(yarpJNI.new_Value__SWIG_3(x), true);
  }

  public Value(String str, boolean isVocab) {
    this(yarpJNI.new_Value__SWIG_4(str, isVocab), true);
  }

  public Value(String str) {
    this(yarpJNI.new_Value__SWIG_5(str), true);
  }

  public Value(SWIGTYPE_p_void data, int length) {
    this(yarpJNI.new_Value__SWIG_6(SWIGTYPE_p_void.getCPtr(data), length), true);
  }

  public Value(Value alt) {
    this(yarpJNI.new_Value__SWIG_7(Value.getCPtr(alt), alt), true);
  }

  public boolean isBool() {
    return yarpJNI.Value_isBool(swigCPtr, this);
  }

  public boolean isInt() {
    return yarpJNI.Value_isInt(swigCPtr, this);
  }

  public boolean isInt64() {
    return yarpJNI.Value_isInt64(swigCPtr, this);
  }

  public boolean isString() {
    return yarpJNI.Value_isString(swigCPtr, this);
  }

  public boolean isDouble() {
    return yarpJNI.Value_isDouble(swigCPtr, this);
  }

  public boolean isList() {
    return yarpJNI.Value_isList(swigCPtr, this);
  }

  public boolean isDict() {
    return yarpJNI.Value_isDict(swigCPtr, this);
  }

  public boolean isVocab() {
    return yarpJNI.Value_isVocab(swigCPtr, this);
  }

  public boolean isBlob() {
    return yarpJNI.Value_isBlob(swigCPtr, this);
  }

  public boolean asBool() {
    return yarpJNI.Value_asBool(swigCPtr, this);
  }

  public int asInt() {
    return yarpJNI.Value_asInt(swigCPtr, this);
  }

  public SWIGTYPE_p_YARP_INT64 asInt64() {
    return new SWIGTYPE_p_YARP_INT64(yarpJNI.Value_asInt64(swigCPtr, this), true);
  }

  public int asVocab() {
    return yarpJNI.Value_asVocab(swigCPtr, this);
  }

  public double asDouble() {
    return yarpJNI.Value_asDouble(swigCPtr, this);
  }

  public String asString() {
    return yarpJNI.Value_asString(swigCPtr, this);
  }

  public Bottle asList() {
    long cPtr = yarpJNI.Value_asList(swigCPtr, this);
    return (cPtr == 0) ? null : new Bottle(cPtr, false);
  }

  public Property asDict() {
    long cPtr = yarpJNI.Value_asDict(swigCPtr, this);
    return (cPtr == 0) ? null : new Property(cPtr, false);
  }

  public Searchable asSearchable() {
    long cPtr = yarpJNI.Value_asSearchable(swigCPtr, this);
    return (cPtr == 0) ? null : new Searchable(cPtr, false);
  }

  public String asBlob() {
    return yarpJNI.Value_asBlob(swigCPtr, this);
  }

  public long asBlobLength() {
    return yarpJNI.Value_asBlobLength(swigCPtr, this);
  }

  public boolean read(ConnectionReader connection) {
    return yarpJNI.Value_read(swigCPtr, this, ConnectionReader.getCPtr(connection), connection);
  }

  public boolean write(ConnectionWriter connection) {
    return yarpJNI.Value_write(swigCPtr, this, ConnectionWriter.getCPtr(connection), connection);
  }

  public Value find(String key) {
    return new Value(yarpJNI.Value_find(swigCPtr, this, key), false);
  }

  public boolean isEqual(Value alt) {
    return yarpJNI.Value_isEqual__SWIG_0(swigCPtr, this, Value.getCPtr(alt), alt);
  }

  public boolean notEqual(Value alt) {
    return yarpJNI.Value_notEqual__SWIG_0(swigCPtr, this, Value.getCPtr(alt), alt);
  }

  public boolean isEqual(String alt) {
    return yarpJNI.Value_isEqual__SWIG_1(swigCPtr, this, alt);
  }

  public boolean notEqual(String alt) {
    return yarpJNI.Value_notEqual__SWIG_1(swigCPtr, this, alt);
  }

  public void fromString(String str) {
    yarpJNI.Value_fromString(swigCPtr, this, str);
  }

  public String toString() {
    return yarpJNI.Value_toString(swigCPtr, this);
  }

  public Value create() {
    long cPtr = yarpJNI.Value_create(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public Value clone_c() {
    long cPtr = yarpJNI.Value_clone_c(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public int getCode() {
    return yarpJNI.Value_getCode(swigCPtr, this);
  }

  public boolean isNull() {
    return yarpJNI.Value_isNull(swigCPtr, this);
  }

  public boolean isLeaf() {
    return yarpJNI.Value_isLeaf(swigCPtr, this);
  }

  public static Value makeInt(int x) {
    long cPtr = yarpJNI.Value_makeInt(x);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeDouble(double x) {
    long cPtr = yarpJNI.Value_makeDouble(x);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeString(String str) {
    long cPtr = yarpJNI.Value_makeString(str);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeVocab(int v) {
    long cPtr = yarpJNI.Value_makeVocab__SWIG_0(v);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeVocab(String str) {
    long cPtr = yarpJNI.Value_makeVocab__SWIG_1(str);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeBlob(SWIGTYPE_p_void data, int length) {
    long cPtr = yarpJNI.Value_makeBlob(SWIGTYPE_p_void.getCPtr(data), length);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeList() {
    long cPtr = yarpJNI.Value_makeList__SWIG_0();
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeList(String txt) {
    long cPtr = yarpJNI.Value_makeList__SWIG_1(txt);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeValue(String txt) {
    long cPtr = yarpJNI.Value_makeValue(txt);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value getNullValue() {
    return new Value(yarpJNI.Value_getNullValue(), false);
  }

  public String toString_c() {
    return yarpJNI.Value_toString_c(swigCPtr, this);
  }

}
