/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Vector extends Portable {
  private long swigCPtr;

  protected Vector(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.Vector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Vector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Vector() {
    this(yarpJNI.new_Vector__SWIG_0(), true);
  }

  public Vector(long s) {
    this(yarpJNI.new_Vector__SWIG_1(s), true);
  }

  public Vector(long s, double def) {
    this(yarpJNI.new_Vector__SWIG_2(s, def), true);
  }

  public Vector(long s, SWIGTYPE_p_double p) {
    this(yarpJNI.new_Vector__SWIG_3(s, SWIGTYPE_p_double.getCPtr(p)), true);
  }

  public Vector(Vector r) {
    this(yarpJNI.new_Vector__SWIG_4(Vector.getCPtr(r), r), true);
  }

  public void size(long s) {
    yarpJNI.Vector_size__SWIG_0(swigCPtr, this, s);
  }

  public void resize(long s) {
    yarpJNI.Vector_resize__SWIG_0(swigCPtr, this, s);
  }

  public void resize(long size, double def) {
    yarpJNI.Vector_resize__SWIG_1(swigCPtr, this, size, def);
  }

  public long size() {
    return yarpJNI.Vector_size__SWIG_1(swigCPtr, this);
  }

  public long length() {
    return yarpJNI.Vector_length(swigCPtr, this);
  }

  public void zero() {
    yarpJNI.Vector_zero(swigCPtr, this);
  }

  public String toString(int precision, int width) {
    return yarpJNI.Vector_toString__SWIG_0(swigCPtr, this, precision, width);
  }

  public String toString(int precision) {
    return yarpJNI.Vector_toString__SWIG_1(swigCPtr, this, precision);
  }

  public String toString() {
    return yarpJNI.Vector_toString__SWIG_2(swigCPtr, this);
  }

  public Vector subVector(long first, long last) {
    return new Vector(yarpJNI.Vector_subVector(swigCPtr, this, first, last), true);
  }

  public boolean setSubvector(int position, Vector v) {
    return yarpJNI.Vector_setSubvector(swigCPtr, this, position, Vector.getCPtr(v), v);
  }

  public SWIGTYPE_p_double data() {
    long cPtr = yarpJNI.Vector_data__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public boolean isEqual(Vector r) {
    return yarpJNI.Vector_isEqual(swigCPtr, this, Vector.getCPtr(r), r);
  }

  public void push_back(double elem) {
    yarpJNI.Vector_push_back(swigCPtr, this, elem);
  }

  public void pop_back() {
    yarpJNI.Vector_pop_back(swigCPtr, this);
  }

  public SWIGTYPE_p_void getGslVector() {
    long cPtr = yarpJNI.Vector_getGslVector__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_double access(long i) {
    return new SWIGTYPE_p_double(yarpJNI.Vector_access__SWIG_0(swigCPtr, this, i), false);
  }

  public void clear() {
    yarpJNI.Vector_clear(swigCPtr, this);
  }

  public boolean read(ConnectionReader connection) {
    return yarpJNI.Vector_read(swigCPtr, this, ConnectionReader.getCPtr(connection), connection);
  }

  public boolean write(ConnectionWriter connection) {
    return yarpJNI.Vector_write(swigCPtr, this, ConnectionWriter.getCPtr(connection), connection);
  }

  public double get(int j) {
    return yarpJNI.Vector_get(swigCPtr, this, j);
  }

  public void set(int j, double v) {
    yarpJNI.Vector_set(swigCPtr, this, j, v);
  }

}
