/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class VectorBase extends Portable {
  private long swigCPtr;

  protected VectorBase(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.VectorBase_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_VectorBase(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int getElementSize() {
    return yarpJNI.VectorBase_getElementSize(swigCPtr, this);
  }

  public long getListSize() {
    return yarpJNI.VectorBase_getListSize(swigCPtr, this);
  }

  public String getMemoryBlock() {
    return yarpJNI.VectorBase_getMemoryBlock(swigCPtr, this);
  }

  public void resize(long size) {
    yarpJNI.VectorBase_resize(swigCPtr, this, size);
  }

  public boolean read(ConnectionReader connection) {
    return yarpJNI.VectorBase_read(swigCPtr, this, ConnectionReader.getCPtr(connection), connection);
  }

  public boolean write(ConnectionWriter connection) {
    return yarpJNI.VectorBase_write(swigCPtr, this, ConnectionWriter.getCPtr(connection), connection);
  }

}
