/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public interface yarpConstants {
  public final static int YARP_CONSTSTRING_IS_STD_STRING = yarpJNI.YARP_CONSTSTRING_IS_STD_STRING_get();
  public final static int BOTTLE_TAG_INT = yarpJNI.BOTTLE_TAG_INT_get();
  public final static int BOTTLE_TAG_VOCAB = yarpJNI.BOTTLE_TAG_VOCAB_get();
  public final static int BOTTLE_TAG_DOUBLE = yarpJNI.BOTTLE_TAG_DOUBLE_get();
  public final static int BOTTLE_TAG_STRING = yarpJNI.BOTTLE_TAG_STRING_get();
  public final static int BOTTLE_TAG_BLOB = yarpJNI.BOTTLE_TAG_BLOB_get();
  public final static int BOTTLE_TAG_INT64 = yarpJNI.BOTTLE_TAG_INT64_get();
  public final static int BOTTLE_TAG_LIST = yarpJNI.BOTTLE_TAG_LIST_get();
  public final static int BOTTLE_TAG_DICT = yarpJNI.BOTTLE_TAG_DICT_get();
  public final static int FORMAT_NULL = yarpJNI.FORMAT_NULL_get();
  public final static int FORMAT_ANY = yarpJNI.FORMAT_ANY_get();
  public final static int FORMAT_PGM = yarpJNI.FORMAT_PGM_get();
  public final static int FORMAT_PPM = yarpJNI.FORMAT_PPM_get();
  public final static int FORMAT_NUMERIC = yarpJNI.FORMAT_NUMERIC_get();

}
