/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class yarp implements yarpConstants {
  public static void typedReaderMissingCallback() {
    yarpJNI.typedReaderMissingCallback();
  }

  public static int PAD_BYTES(int len, int pad) {
    return yarpJNI.PAD_BYTES(len, pad);
  }

  public static boolean read(ImageRgb dest, String src) {
    return yarpJNI.read__SWIG_0(ImageRgb.getCPtr(dest), dest, src);
  }

  public static boolean read(SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t dest, String src) {
    return yarpJNI.read__SWIG_1(SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t.getCPtr(dest), src);
  }

  public static boolean read(ImageRgba dest, String src) {
    return yarpJNI.read__SWIG_2(ImageRgba.getCPtr(dest), dest, src);
  }

  public static boolean read(ImageMono dest, String src) {
    return yarpJNI.read__SWIG_3(ImageMono.getCPtr(dest), dest, src);
  }

  public static boolean read(ImageFloat dest, String src) {
    return yarpJNI.read__SWIG_4(ImageFloat.getCPtr(dest), dest, src);
  }

  public static boolean write(ImageRgb src, String dest) {
    return yarpJNI.write__SWIG_0(ImageRgb.getCPtr(src), src, dest);
  }

  public static boolean write(SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t src, String dest) {
    return yarpJNI.write__SWIG_1(SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t.getCPtr(src), dest);
  }

  public static boolean write(ImageRgba src, String dest) {
    return yarpJNI.write__SWIG_2(ImageRgba.getCPtr(src), src, dest);
  }

  public static boolean write(ImageMono src, String dest) {
    return yarpJNI.write__SWIG_3(ImageMono.getCPtr(src), src, dest);
  }

  public static boolean write(ImageFloat src, String dest) {
    return yarpJNI.write__SWIG_4(ImageFloat.getCPtr(src), src, dest);
  }

  public static boolean write(Image src, String dest) {
    return yarpJNI.write__SWIG_5(Image.getCPtr(src), src, dest);
  }

}
