/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alecive_yarpdroid_MainActivity */

#ifndef _Included_com_alecive_yarpdroid_MainActivity
#define _Included_com_alecive_yarpdroid_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alecive_yarpdroid_MainActivity
 * Method:    initNetwork
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_alecive_yarpdroid_MainActivity_initNetwork
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
