/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alecive_yarpdroid_MainActivity */

#ifndef _Included_com_alecive_yarpdroid_MainActivity
#define _Included_com_alecive_yarpdroid_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alecive_yarpdroid_MainActivity
 * Method:    initNetwork
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_MainActivity_initNetwork
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
