/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alecive_yarpdroid_demoCTPFragment */

#ifndef _Included_com_alecive_yarpdroid_demoCTPFragment
#define _Included_com_alecive_yarpdroid_demoCTPFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alecive_yarpdroid_demoCTPFragment
 * Method:    register
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_demoCTPFragment_register
  (JNIEnv *, jobject);

/*
 * Class:     com_alecive_yarpdroid_demoCTPFragment
 * Method:    sendAction
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_demoCTPFragment_sendAction
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_alecive_yarpdroid_demoCTPFragment
 * Method:    createBufferedPort
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_demoCTPFragment_createBufferedPort
  (JNIEnv *, jobject);

/*
 * Class:     com_alecive_yarpdroid_demoCTPFragment
 * Method:    destroyBufferedPort
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_demoCTPFragment_destroyBufferedPort
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
