/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alecive_yarpdroid_yarpviewFragment */

#ifndef _Included_com_alecive_yarpdroid_yarpviewFragment
#define _Included_com_alecive_yarpdroid_yarpviewFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alecive_yarpdroid_yarpviewFragment
 * Method:    register
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_yarpviewFragment_register
  (JNIEnv *, jobject);

/*
 * Class:     com_alecive_yarpdroid_yarpviewFragment
 * Method:    gettImgReceivedonPort
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_alecive_yarpdroid_yarpviewFragment_getImgReceivedonPort
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_alecive_yarpdroid_yarpviewFragment
 * Method:    createBufferedImgPortL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alecive_yarpdroid_yarpviewFragment_createBufferedImgPortL
  (JNIEnv *, jobject);

/*
 * Class:     com_alecive_yarpdroid_yarpviewFragment
 * Method:    destroyBufferedImgPortL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alecive_yarpdroid_yarpviewFragment_destroyBufferedImgPortL
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
