/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alecive_yarpdroid_MainActivity_TabsPagerAdapter */

#ifndef _Included_com_alecive_yarpdroid_MainActivity_TabsPagerAdapter
#define _Included_com_alecive_yarpdroid_MainActivity_TabsPagerAdapter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
