/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alecive_yarpdroid_cameraIntentFragment */

#ifndef _Included_com_alecive_yarpdroid_cameraIntentFragment
#define _Included_com_alecive_yarpdroid_cameraIntentFragment
#ifdef __cplusplus
extern "C" {
#endif
#undef com_alecive_yarpdroid_cameraIntentFragment_ACTION_TAKE_PHOTO_B
#define com_alecive_yarpdroid_cameraIntentFragment_ACTION_TAKE_PHOTO_B 1L
#undef com_alecive_yarpdroid_cameraIntentFragment_ACTION_TAKE_PHOTO_S
#define com_alecive_yarpdroid_cameraIntentFragment_ACTION_TAKE_PHOTO_S 2L
#undef com_alecive_yarpdroid_cameraIntentFragment_ACTION_TAKE_VIDEO
#define com_alecive_yarpdroid_cameraIntentFragment_ACTION_TAKE_VIDEO 3L
/*
 * Class:     com_alecive_yarpdroid_cameraIntentFragment
 * Method:    createBufferedPort
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_cameraIntentFragment_createBufferedPort
  (JNIEnv *, jobject);

/*
 * Class:     com_alecive_yarpdroid_cameraIntentFragment
 * Method:    writeOntoBufferedPort
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_alecive_yarpdroid_cameraIntentFragment_writeOntoBufferedPort
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_alecive_yarpdroid_cameraIntentFragment
 * Method:    destroyBufferedPort
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_cameraIntentFragment_destroyBufferedPort
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
