/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alecive_yarpdroid_yarpviewFragment */

#ifndef _Included_com_alecive_yarpdroid_yarpviewFragment
#define _Included_com_alecive_yarpdroid_yarpviewFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alecive_yarpdroid_yarpviewFragment
 * Method:    register
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_yarpviewFragment_register
  (JNIEnv *, jobject);

/*
 * Class:     com_alecive_yarpdroid_yarpviewFragment
 * Method:    createBufferedImgPortL
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_yarpviewFragment_createBufferedImgPortL
  (JNIEnv *, jobject);

/*
 * Class:     com_alecive_yarpdroid_yarpviewFragment
 * Method:    destroyBufferedImgPortL
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_yarpviewFragment_destroyBufferedImgPortL
  (JNIEnv *, jobject);

/*
 * Class:     com_alecive_yarpdroid_yarpviewFragment
 * Method:    createBufferedMonoIPort
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_yarpviewFragment_createBufferedMonoIPort
  (JNIEnv *, jobject);

/*
 * Class:     com_alecive_yarpdroid_yarpviewFragment
 * Method:    destroyBufferedMonoIPort
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_yarpviewFragment_destroyBufferedMonoIPort
  (JNIEnv *, jobject);

/*
 * Class:     com_alecive_yarpdroid_yarpviewFragment
 * Method:    sendTouchEventsonMonoIPort
 * Signature: (Ljava/lang/String;IID)Z
 */
JNIEXPORT jboolean JNICALL Java_com_alecive_yarpdroid_yarpviewFragment_sendTouchEventsonMonoIPort
  (JNIEnv *, jobject, jstring, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
