/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <unistd.h>
/* Header for class com_alecive_yarpdroid_MainActivity_hello */

#define LOG_TAG "com.alecive.yarpdroid C++"

extern "C" {
    JNIEXPORT jstring JNICALL
    Java_com_alecive_yarpdroid_MainActivity_yarpdroid(JNIEnv *env, jobject obj);

    void Java_com_alecive_yarpdroid_MainActivity_testCallback(JNIEnv *env, jobject obj);
}

