/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alecive_yarpdroid_STTFragment */

#ifndef _Included_com_alecive_yarpdroid_STTFragment
#define _Included_com_alecive_yarpdroid_STTFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alecive_yarpdroid_STTFragment
 * Method:    testCallbackStatic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alecive_yarpdroid_STTFragment_testCallbackStatic
  (JNIEnv *, jclass);

/*
 * Class:     com_alecive_yarpdroid_STTFragment
 * Method:    testCallbackNonStatic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alecive_yarpdroid_STTFragment_testCallbackNonStatic
  (JNIEnv *, jobject);

/*
 * Class:     com_alecive_yarpdroid_STTFragment
 * Method:    createBufferedPort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alecive_yarpdroid_STTFragment_createBufferedPort
  (JNIEnv *, jobject);

/*
 * Class:     com_alecive_yarpdroid_STTFragment
 * Method:    writeOntoBufferedPort
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_alecive_yarpdroid_STTFragment_writeOntoBufferedPort
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_alecive_yarpdroid_STTFragment
 * Method:    destroyBufferedPort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alecive_yarpdroid_STTFragment_destroyBufferedPort
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
