/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alecive_yarpdroid_MainActivity_networkInitializer */

#ifndef _Included_com_alecive_yarpdroid_MainActivity_networkInitializer
#define _Included_com_alecive_yarpdroid_MainActivity_networkInitializer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
